# -*- mode: Org; org-download-image-dir: "../../images"; -*-
#+BEGIN_COMMENT
.. title: 笑话
.. slug: joke
#+END_COMMENT
* 白字
《论语》中的“郁郁乎文哉”，讹作“都都平丈我”
* 政治笑话
- 如何评价冯玉祥写的《我所认识的蒋介石》这本书?
- 从这本书认识不了蒋介石，倒是能认识冯玉祥。
- 路过一哨所，门口立一牌子，上写【卫兵神圣，不容侵犯】。读来感慨万千，我曾公知过，当时看到这类牌子的想法是【毒菜的走狗！】，我也曾五毛过，那时看到这牌子的想法是【人民子弟兵最威武！】，现在的想法是【这里的兵哥哥都很帅吗？！那么多人想侵犯他们？】
** 刘晓波的和平奖

#+BEGIN_EXAMPLE
 问:有没有中国人获得诺贝尔奖?
 答:有,但他们都拿着外国国籍。(赛珍珠,丁肇中,李远哲,朱棣文,崔琦,钱永健)
 问:有没有中国公民获得过诺贝尔奖?
 答:有,但他们都是中华民国的公民。(李政道,杨振宁)
 问:有没有新中国的公民获得过诺贝尔奖?
 答:有,但他不承认自己是中国公民。(高行健)
 问:有没有承认自己是中国人的新中国公民获得诺贝尔奖?
 答:有,但是我们不承认他是中国公民。(达赖)
 问:有没有承认自己是中国公民,国家也承认他是新中国公民的诺贝尔奖获得者?
 答:有,但他在新中国的监狱里。(刘晓波) 
#+END_EXAMPLE

 宣称"我没有敌人"的刘晓波获得诺贝尔和平奖,兲朝老大哥非常恼火,冥思苦想后确定了一个更响亮的口号--"我没有朋友"!

 评奖的这帮人太狠了,每当钱不够时,就发给一个无法领奖的人。

 诺贝尔官网网友留言:我不知道刘先生是谁,但是我为中国人能够获得诺贝尔奖而高兴。他一定是一名好党员,我们中国人民的好干部,为人民做实事的好领导。

 中国是一个热爱和平的国家,却讨厌和平奖。

新华社:中国一名服刑人员在改造期间轻而易举获得了诺贝尔奖,充分体现社会主义法制国家的优越性。

#+BEGIN_EXAMPLE
 胡锦涛:刘晓波交代了吗?
 专案组:他彻底交代了,我们查证属实。
 胡锦涛:联邦共和国出自何处?
 专案组:中国共产党第二次代表大会公报。原文提法是:建立一个自由的联邦共和国。多了个"自由"。
 胡锦涛:那...那军队国家化呢?
 专案组:也查清了!出自《周恩来选集》。原文提法是:必须实现军队国家化。多了个"必须实现"。
 胡锦涛:那...那...那赞美西方民主制度出自何处?
 专案组:《新华日报》社论。原文提法是:美国代表了民主社会。多了个"美国代表"。
 胡锦涛:那...那...那解除党禁呢?
 专案组:毛太祖反对国民党时提出来的口号!原文提法多了个"打倒一党专政"!
 胡锦涛:那...那...那...那结社自由,言论自由,出版自由呢?
 专案组:这些,宪法里全有! 
#+END_EXAMPLE

 刘晓波抄了一遍宪法,结果判了11年。

#+BEGIN_EXAMPLE
 忽然想到一个刑法的技术问题:拿了诺奖减刑不?
 根据刑法第78条的规定,有下列重大立功表现之一的,应当减刑:
 (6)对国家和社会有其他重大贡献的。 
#+END_EXAMPLE

#+BEGIN_EXAMPLE
 刘晓波获奖是我党政法委无数次严密实验的科学结晶:
 高智晟判三年不行,胡佳判三年半不行,陈光诚判四年半不行,谭作人判五年也不行...
 终于,刘晓波判11年--球进了!
 感谢国家!感谢党! 
#+END_EXAMPLE
* 编程笑话
6. 如今的编程是一场程序员和上帝的竞赛，程序员要开发出更大更好、傻瓜都会用到软件。而上帝在努力创造出更大更傻的傻瓜。目前为止，上帝是赢的。(Rick Cook)
* 逻辑笑话
- “嗟来之食”这个典故很有趣：“我靠你都穷到要死了还这么拽？”“废话老子就是因为这么拽才穷到要死的！”——其实，这是一种看似古怪却常见的逻辑，比如“你都这么蠢了还不用功？”“你都这么难看了还不打扮？”“事情都火烧眉毛了你还在拖延？”“你都混成这样了还信正能量？”
