# -*- mode: Org; org-download-image-dir: "../../images"; -*-
#+BEGIN_COMMENT
.. title: 名言名句
.. slug: Quotations
#+END_COMMENT

#+BEGIN_QUOTE
幼有神童之誉，少怀壮志，长而无闻，终与草木同朽。 

- 冯唐《墓志铭》
#+END_QUOTE

#+BEGIN_QUOTE
三十五年，楚伐随。是也。随曰：“我无罪。”楚曰：“我蛮夷也。
#+END_QUOTE

#+BEGIN_QUOTE
在中国，任何超脱飞扬的思想都会砰然坠地——现实的引力实在是太沉重了

──《三体》
#+END_QUOTE

#+BEGIN_QUOTE
胸有激雷而面如平湖者，可以拜上将军也。
#+END_QUOTE

#+BEGIN_QUOTE
直至近代诗僧曼殊，仍在延续这样的梦：

“谁知词客蓬山里，烟雨楼台梦六朝。”
#+END_QUOTE

#+BEGIN_QUOTE
往事依稀浑似梦，都随风雨到心头
#+END_QUOTE

#+BEGIN_QUOTE
死犹未肯输心去，贫亦其能奈我何。——黄宗羲《山居杂咏》 
#+END_QUOTE

#+BEGIN_QUOTE
万籁生山，一星在水。
#+END_QUOTE

#+BEGIN_QUOTE
添得情怀转萧索，始知伶俐不如痴。
#+END_QUOTE

#+BEGIN_QUOTE
优游好岁月，富贵到白头。
#+END_QUOTE

北京无名英雄纪念广场， 纪念上世纪五十年代为国家统一、人民解放事业牺牲于台湾的大批隐蔽战线无名英雄而建。 主碑文这样写道：

#+BEGIN_QUOTE 
天下有大勇者，智不能测，刚不能制，猝然临之而不惊，无朕加之而不怒，此其志甚远，所怀甚大也。所怀者何？天下有饥者，如己之饥；天下有溺者，如己之溺耳。民族危急，别亲离子而赴水火，易面事敌而求大同。风萧水寒，旌霜履血，或成或败，或囚或殁，人不知之，乃至陨后无名。 铭曰：

呜呼！大音希声，大象无形。来兮精魄，安兮英灵。长河为咽，青山为证；岂曰无声？河山即名！

人有所忘，史有所轻。一统可期，民族将兴。肃之嘉石，沐手勒铭。噫我子孙，代代永旌。
#+END_QUOTE

#+BEGIN_QUOTE
危邦不入，乱邦不居
#+END_QUOTE

#+BEGIN_QUOTE
我未成名卿未嫁，可能俱是不如人
#+END_QUOTE

#+BEGIN_QUOTE
嗟乎，子卿！夫复何言？相去万里，人绝路殊，生为别世之人，死为异域之鬼，长与足下，生死辞矣。幸谢故人，勉事圣君。足下胤子无恙，勿以为念。努力自爱。时因北风，复惠德音。李陵顿首。
#+END_QUOTE

#+BEGIN_QUOTE
慣於長夜過春時
　　七言律詩　　　顯示自動注释

題注：1931年作

該節寫道：一九五七年羅稷南向毛主席提出一个大膽的設想疑問：要是今天魯迅還活著，他可能會怎樣？毛回答説：“以我的估計，要麽是關在牢裏還是要寫，要麽他識大體不做聲。”

慣于長夜過春時，挈婦將雛鬢有絲。夢裏依稀慈母淚，城頭變幻大王旗。

忍看朋輩成新鬼，怒向刀叢覓小詩。吟罷低眉無寫處，月光如水照緇衣。

按：这首诗见于《南腔北调集·为了忘却的纪念》，为悼念“左联”五烈士而作。
#+END_QUOTE
* 无情对
缘由心生，爱因斯坦。

堪叹我南船北马，察哈尔右翼前旗。

佳人苹果脸，瑞士葡萄牙。

公门桃李争荣日，法国荷兰比利时。

浩如雷公，切比雪夫；

托怀明月，拉格朗日；

缘由心生，爱因斯坦，

一匹天青缎，六味地黄丸。

外婆磨针，内公切线；

长春花碱，安息香酸。

安非他命，如是我闻

* 对联
磨砺以须 问天下头颅几许 及锋而试 看老夫手段如何
 －－ 石达开 题理发店
** 挽联
*** 古龙
 小李飞刀成绝响，人间不见楚留香。

