#+BEGIN_COMMENT
.. title: 2017年人文工物新生赛淘汰赛──“科技发展应不应该有伦理界限”
.. slug: 2017nian-ren-wen-gong-wu-xin-sheng-sai-tao-tai-sai-ke-ji-fa-zhan-ying-bu-ying-gai-you-lun-li-jie-xian
.. date: 2016-11-27 21:21:51 UTC+08:00
.. tags: 
.. category: 辩论
.. link: 
.. description: 
.. type: text
#+END_COMMENT


今天去听索拉带的小朋友的比赛，题目叫做“科技发展应不应该有伦理界限”。02年的辩题，14年前就被讨论是不是持方不公，现在还在打，也实在是醉。

#+HTML: <!--TEASER_END-->

* 场上局势

正方的立论有三个点，反方立论有两个点，然而，之后的整场比赛，这些点都再也没有出现过。。。

你们一定很好奇他们在剩下的一个小时里在干什么……

本场比赛达成的共识有：
1. 双方都认为，有一些东西是因为伦理原因，打死都不能做的…
   - 你懂得，这个共识在大部分评委心证里是反方大劣
2. 双方都认为，伦理划出来的那条线是注定要被打破的…
   - 你懂得，这个共识在大部分评委心证里是正方大劣

在共识上，双方的争议点
1. 针对共识1
   - 反方的应对方案叫做，这个玩意是底线，不是界限。
   - 为什么有伦理底线不是伦理界限？反方并没讲。。。。
2. 针对共识2
   - 正方说，这就是我们的界限的定义啦
   - 反方在自由辩质疑──这不是伦理追着科技走吗？这怎么能叫界限呢？
   - 单独看这句话是不错啦。可是你共识1里刚承认有些东西打死都不能做，这些伦理怎么追着科技走的矛盾要处理一下吧？于是回到共识1,

于是反方输掉了。

#+BEGIN_EXAMPLE
反方赛前的悲观使得他们并不相信能赢，于是他们并没有一条能证明已方立场的逻辑线…非常的令人难过 
#+END_EXAMPLE

* 破题

其实，劣势持方有个好处，叫做对手可预期。

比如说，这个题就让界限是那些所谓的底线好咯。我们只需要处理，是不是为了科技发展，人可以无恶不作── *当然不是，我们要尽量不做恶，但是我们要保留做“恶”的权力* 。

那些我们通常认为天经地义的伦理原则常常有被打破的时候。

- 比如说不做活体实验，不伤害人类健康的两个原则，在我们药物临床实验中其实就是被打破的，因为个体差异大，很有可能会有实验者受到伤害。再比如航空航天的先驱烈士们。这个时候，我们会诉诸“自愿”，要求实验者自愿参加。
- 那么自愿就是不可打破的底线了么。并不是，心理学实验中常见这样的设计，会向被试展示虚假的实验意图，以防被试主观操纵实验结果。这种时候被试的自愿，就是不了解真实情况的伪自愿。

明白吗？展示科研工作者迫不得已与奉献牺牲。

这个时候再去告诉大家，自然规律是先于人类存在，并将在人类灭亡后继续存在，科学发展并不以科学家的主观意志为转移，我们只能努力以我们可能付出的最小代价去了解它。

----------------------------------

反直观反心证的劣势立场，如何去贴评委和观众的心证 ── *展示你的纠结痛苦与无可奈何* 。

* 附录

贴一下我想到的立论（结辩）框架

#+BEGIN_QUOTE
1从科技发展的领域来说，未知的领域无法用已有知识归纳的伦理来约束

*这个没啥争议*

2从手段来说：现行的医学伦理——科学发展不存在伦理界限，只要收益大于成本就可以施行，哪怕有不利影响（多重手段选伤害最小的）

世界医学协会的日内瓦声明用"病人的健康必须是我们首先考虑的事"一句话对医生在道义上
加以约束。国际医学道德标准的规定宣称："只有在符合病人的利益时，医生才可提供可能
对病人的生理及心理状态产生不利影响的医学措施"。

*这个就是破题的前半部分*

3从价值上来说，这个十四年前的辩题认为可能设立界限来限制科技的发展，体现了人类的狂妄。科学规律存在于人类诞生之前，亦将持续于人类灭亡以后。科技有其内在发展规律，浩浩汤汤，虽不能说顺之者昌，逆之者亡，却也难以估测，如何确定该限制什么？(凯文凯利有本书叫作失控)举个例子，谁会一开始意识到大数据会导致人在网络上不再存在隐私？所能做的是拥抱变化
#+END_QUOTE
