# -*- mode: Org; org-download-image-dir: "../images"; -*-
#+BEGIN_COMMENT
.. title: 福柯“谱系学”及《知识考古学》
.. slug: fu-ke-pu-xi-xue-ji-zhi-shi-kao-gu-xue
.. date: 2017-02-05 19:39:17 UTC+08:00
.. tags:  reading
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT




* 福柯的谱系学（généalogie）
 
 
谱系学是福柯从尼采那里借用的概念。


#+BEGIN_QUOTE
要厘清福柯的谱系学是什么意思，必须首先理解他提出这个概念所针对的是西方现代的历史观，在《尼采、谱系学和历史》一文中他对西方形而上学的历史观提出了强烈的批判，他认为西方普通的历史学实际上引入一个超历史的视点，这种历史的作用是把多样性最终化约为单一的普遍时间，从而组合成一个完全自我封闭的总体，这种历史总是使人把过去的种种事件都和解为一个统一体。“这种历史带着世界的终极的眼光来看待过去的一些事物。这种历史学家的历史在时间之外寻找一个支点，并妄称其判断的基础是一种预示世界终极的客观性。然而，这种历史却假定存在了永恒真理、灵魂不朽以及始终自我同一的意识。“这种超历史视角所支配的，最终就是一种形而上学的历史。

这就是为什么福柯拒绝把自己的工作称为历史研究。他在《必须保卫社会》这样来定义谱系学方法和立场：“谱系学，相对与把知识注册在专属科学权力的等级中的规划，是一项解放历史知识使其摆脱奴役的事业，也就是说它有能力对统一的、形式化的和科学的话语进行反抗和斗争。局部知识[……]的复兴反对科学和认识的等级化及其固有权力，这就是无序的、片断的谱系学的计划。[……]考古学，这是属于分析局部话语性的方法，以及从如此描述的局部话语性开始，使解脱出来的知识运转起来的谱系学策略。”简言之，福柯认为西方的现代历史学预设了时间的方向，表现了一种进步主义的历史观，试图在纷繁复杂的世界中确定和规划这个世界的先验起点及其目的。虽未明言，但是不难看出，福柯要挑战的知识体系和话语秩序的典型代表就是黑格尔式的哲学。谱系学是非整体化的，反对知识的等级和神性，反对进步主义，强调事物和历史变迁的偶然性。福柯不认为我们的知识是一个走向形而上的纯粹真理的线性过程，他重视的是，权力和各种偶然因素怎样构成了知识生成的现实可能性条件。例如福柯在《不正常的人》中提出，现代医学中的精神病学的发展与权力对家庭和人口的干预密不可分，随着权力对于家庭和卫生的控制，精神病学把人区分为正常的人和不正常的人。这个学科的起源并不是“关于人的真理”这样一个形而上学主题在现实世界的必然历史发展，而是基于一系列权力运作和知识生产的相互关系。
福柯的谱系学可以说是在敲打和破坏西方现代历史哲学的地基，成为所谓后现代思潮的重要概念之一。对这一概念勾画一个大致的轮廓也并不困难，中国的学者已经发表了不少相关的论文。然而，généalogie（谱系学）之命名还是让人感到困惑不已，无论在法汉字典还是在已有的翻译和介绍中，这个词大部分都被译为谱系学。另外还有一种翻译是系谱学，然而与其说系谱学是一种更加精细的翻译，不如说它表明了译者翻译généalogie这个概念时的焦虑：感觉谱系学这个词不对劲，但是又不知怎么办，于是采用系谱学的说法，使它与常用词汇保持一点距离，从而可以用定义的方式使这个词接纳与常见的意思看上去无关的内容。这种术语上的困惑导致了对这个概念理解上一些混乱，使我们难以做更精细的辨析。智河在《福柯系谱学探微》中说到：“要实现第一个任务（即追溯对象的出身)，首先要破除人们千百年来形成的关于“本质、“本源”、“同一”的幻想。“而张艳玲在《解读福柯：从“知识考古学”到“系谱学”》中则认为：“    20世纪70年代，福柯用“系谱学”（genealogy）替代了他的‘考古学’。‘系谱学’这一概念来自尼采，尼采用它来说明道德偏见的起源。福柯的“系谱学”也是关于起源的考察，系谱学的原义就是关于家族世系、血统关系和重要人物事迹的科学，也就是对事物的起源和演变过程的考察。它与考古学的性质并无不同，例如，二者都试图从微观的角度重新考察社会历史，都试图打断历史连续性的巨大链条，倡导非连续性或断续性。“应该说，这两位学者都认识到谱系学的特征在于反形而上学的历史进步观和连续性，强调人类社会进程中的断裂，但是对于谱系学如何对待“起源”问题却有分歧，这个混乱有一定的普遍性。谱系学，无论在中国还是西方，都是一门研究血统承继的学问，其目的就是确定一个家族是如何传承有序，其高贵的血缘如何连续不绝。然而，根据内维尔（Judith Revel）所编撰的《福柯辞典》，福柯的généalogie，“其目的绝非追溯时间的源流，从而建立起历史的连续性，相反，它是要恢复事件的特殊性。”这两个意思之间的关系就像福柯自己常常用的词：有一道裂缝。

在Robert法语字典中，généalogie解释如下：1，祖先的相续关系建立起的血缘源流。2，研究家族的源头和血缘继承的学问。汉语里“谱系”的意思与之非常接近，这个词的翻译几乎完全是榫卯相对，都指的是记述和研究宗族世系或同类事物的历代系统。为什么福柯拒绝承认历史的连续性和继承关系，强调断裂和偶然，却使用了一个让我们更容易联想到连续性和继承关系的术语“谱系学”呢？这个问题不免让福柯的翻译者和研究者感到疑惑和纠结，我们看到，对福柯谱系学的研究文章虽然很多，但是却没有人就这个词本身说清楚为什么福柯要使用谱系学这个术语来替代历史学。

如果摆脱汉语的翻译和字典的解释，直接考察这个西文词的构成本身，也许会给我们带来一些启发。Généalogie，是两个部分组成的，后面的alogie在西语中（英语中是logy）一般意味着“学问、知识和学科”，而前面的gene也是一个常用词根，源自拉丁、希腊词根【gen】（出生，血统，世系，根本）。意思是“出生，创始，新生”等等，《圣经》中的《创世纪》就是用的这个词根（Genèse ，英语是Genesis），当代科技中的“基因”就是gene的音译。Généalogie这个词的构形的原义应该是研究出生的学问。

从这个词意出发，我们恐怕就不难理解福柯为什么从尼采那里借用这个概念了。事实上，无论在尼采还是福柯那里，谱系学都不是用来说明某种概念或话语的家谱是如何继承的，而是强调概念或话语是“如何出生的”。福柯在《尼采、谱系学和历史》一文中提到了尼采对Ursprung（一般译为起源）的两种用法，“第一种不加强调，而且它可以与其他术语例如Entstehung（出现）、 Herkunft（出身）, Abkunft（来源）, Geburt（诞生）替换使用。”但是另一种则与Herkunft（出身）产生了对立：“在《道德谱系学》的这一点上，尼采希望表明Herkunft和Ursprung两个词之间的这种对立是有价值的”。尼采认为Ursprung（起源）是虚幻骗人的东西，不过是人类试图给现实所发生的一切历史事实之上赋予一个合理化的形式，用同一个先验的进程来定义人类实际生活经验，这个东西可以是柏拉图的理念，或者是黑格尔的绝对精神。而福柯眼中的谱系学家则“倾听历史，而不是信奉形而上学，他就会发现事物背后‘有一个完全不同的东西’：那并非一种无时间的、本质的秘密，而是这样的一个秘密，即这些事物都没有本质，或者说，它们的本质都是一点点地从异己的形式中建构出来的。“福柯认为，西方现代的历史学虽然研究的是时间变化的事物，但是却在所谓背后的深层阐释中探寻一个不变的纯洁的本质（超历史），谱系学则强调“事件的出身”，而这个出身常常是不干净的，猥琐低微的。假使我们探究人类的根本出身的尽头，那里站立着一直长毛的猿猴。

起源和出身在日常语言中的语义非常接近，无论在汉语还是在德语中，都是如此。当尼采和福柯把这两个观念对立起来的时候，他们所说的起源是一种特殊的起源，不是指事物在现实的具体境遇中是如何产生的，而是某种固定不变的真理——虚幻的理性建构，这种观念相信现实世界的起源是先验的观念，例如：善恶、道德、真理、拯救等等。而福柯所说的“出身”与日常的用法不同，不是在某个具体的个体上寻找某种可以把他归入某个种族的特征，说他是德国或者是中国人；而是在时间的变迁中发生的具体的有标志性的事件，这些标记本身是混杂的，构成复杂的网络，它们不能被归结为任何一种统一的性质和运动。举例说，“德国人说他们拥有双重灵魂，认为这样就已经深入解释了他们的复杂性；他们上了某种吉利数字的当，或者更恰当地说，他们试图掌握种族上的混杂，而实际上他们正是从这种混杂中产生出来的。”也就是说，当德国人试图通过这种方式确定统一的“我”的时候，就落入了陷阱——他们假装有一个统一的灵魂，其实每一个德国都与另一个德国人不同，他们的出身其实也各个不同，只是被穿上的虚幻的一件叫做“德国人“的衣服。

在大家都认为有一个一致性的地方，谱系学家开始研究其来源和出身，拆解那个“我”，寻找到被人遗忘的种种纷繁复杂的事件的原貌。“谱系学被定义为对“出身”（Herkunft）和“出现”（Entstehung）进行的研究“，这个出身并不具有神一样的高贵的血统，也不代表任何“本质”，所有的事件都是在时间中不断地生成（générer）。这是一种否定连续性，打断继承性，强调异质性的谱系学，它不寻找一个统一的源头，而是分析不同事件在历史中所产生的效果。所以在某种意义上来说，福柯所说的谱系学恰恰是我们的日常语言中所说的谱系学的反面。为了避免日常语义的困扰和误导，陈雪虎先生提议干脆不要用谱系学来翻译généalogie，而是用”出生学“或者”出身学“，这样更准确，更能表达福柯的思想，同时能避免因词语造成的混乱。然而，站在译者的角度，我还是感到犹豫不定。因为造一个新词，确实可以澄清一些理解和思维上的混乱，但是会造成一个术语对应不同汉语词汇的情况，这在福柯的语境中也许没有问题，但是面对其他语境的时候，则有可能造成其他问题，使我们在进行概念的比较研究的时候，造成新的困难。而且，généalogie在西语的环境中，受到日常语义的干扰，对于欧洲人来说其实也可能引起误解，也需要通过详细的辨析和对词形的考查才能把握其特定涵义，那么在翻译到汉语的过程中是不是真的应该消除掉这个词的日常语义？恐怕这个问题对于哲学著作的翻译者来说，始终是纠结难解的问题。


福柯谱系学与历史学的对立，其实中国学者的体会并不很深，也不敏感。原因并不在于中国 学者不能接受其谱系学，不能理解他所说的知识发生的经验性和历史的多变性，而是中国的 传统历史观本来就不太形而上学，更没有福柯视为对手的历史进步主义。网上有一个流传甚 广的黑格尔的名言：“中国没有真正的历史”。当然，黑格尔并没有这样说过，《历史哲学》 中的原话是：“这种历史的详细节目，我们用不着深入考究，因为这种历史本身既然没表现 出有何进展，只会阻碍我们历史的进步。”黑格尔式的形而上学历史观是现代才引入中国的 舶来品，传统上中国历史观与进步主义无关，没有什么超历史的视角，更没有对历史终结的 追求。知识产生于多方面的现实经验，来自可感知的千差万别的具体生活历史，历史并没有 一个终结和目标。福柯谱系学所强调的这些观念，对于中国传统来说，并没有什么格格不入
之处，甚至会感到一种特别的亲切。
#+END_QUOTE
