#+BEGIN_COMMENT
.. title: 机械键盘
.. slug: ji-jie-jian-pan
.. date: 2016-11-23 13:23:59 UTC+08:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT

#+HTML: <!--TEASER_END-->

* 轴
大家只需要明白两个东西就行：触发压力和段落。

触发压力表示触发按键需要的力量，触发压力越大按键越 “硬”。

段落表示是否有段落感。黑轴、灰轴和红轴没有段落，直上直下，一按到底；其他的轴都有段落感，按下的时候会有 “咔哒” 的声音，像按开关一样。

常见的轴是黑轴、青轴和茶轴：
- 黑轴很硬，适合写程序和打游戏；
- 青轴很吵，适合炫耀，不过在办公室要小心被打；
- 茶轴比较低调，比黑轴软，比青轴安静，适合长时间打字。
- 奶轴、白轴和红轴是比较稀有的轴，通俗的说就是价格更贵。
  - 稀有轴中红轴最为知名，基本上是爱好者们的进阶必选轴。
  - 这几年白轴和奶轴也逐渐火起来了，不过总有种四不像的感觉，我个人没什么感觉。

对于第一把键盘来说，可以选择青轴、黑轴或者红轴，从第二把键盘开始你应该就不会问出这个问题了。

* 键帽

拆键帽的时候推荐使用拔键器，否则可能把轴拔断。

常见的键帽有三类：ABS、POM 和 PBT。

ABS 最常见，缺点是容易打油，用时间长了键帽上油光锃亮一层，看着很难受。

POM 稍好于 ABS，常见于原厂（Cherry）键盘，抗打油能力更强，其他方面差别不大。

PBT 质量最高，价格也最高，号称永不打油。不过我用过之后觉得手感不好，跟 ABS 比起来简直可以称之为砂纸。

作者：趸船
链接：https://www.zhihu.com/question/20782493/answer/16161991
来源：知乎


如果是想问使用上面的感觉有何区别的话，我可以简单回答一下：
首先，市面上大部分的普通薄膜键盘乃至机械键盘都是采用了ABS材质的键帽，原因很简单——成本低。但是ABS键帽有个最大的缺点就是容易打油，所谓打油就是键帽使用时间过长后表面会泛油光。可以低头看一下自己的键盘，如果是ABS材质的键帽并且持续使用超过1个月，基本都会有部分油光的出现。正是由于这个原因，为了让键帽的耐用程度和机械键盘匹配，会有部分采用PBT和POM材质的键帽。这两种材质的键帽之间有什么区别？具体的材质区别就不说了，对于键盘玩家来说，关注的还是手感和打油程度。

先说手感，PBT感觉会比较粗糙，键帽表面的颗粒感很明显；而POM表面是很光滑的，个人觉得比全新的ABS的键帽还要光滑。至于那种手感好？我觉得还要看个人喜好。如果需要摩擦力大一些的话，请选择PBT，反之 选择POM。

再说打油程度，网上的评价是POM比PBT更加不容易打油，可能是因为POM本身感觉表面就泛有一层油光，所以不太容易显示出使用的痕迹。但个人使用感受却相反，自己的两把键盘，使用频率差不多，POM键帽的键盘打油程度比PBT的厉害很多。

当然，材质只是一方面，每个生产厂商的制作工艺不同，对于键帽的手感和耐用度都会造成差别。例如现在机械键盘中最火的FILCO，一直使用ABS材质的键帽，但是他的键帽表面有特殊的涂层处理，所以手感和普通的ABS区别很大，有类似PBT的手感。另外，CHERRY原厂的PBT材质，和OEM的PBT材质也有所不同。所以不能仅就材质来区别键帽的好坏。

另外补充一点，POM色彩比较单一，我到现在只看过黑色的POM，如果想要浅色的、彩色的键帽，市面上只有PBT和ABS材质的可以选择。



除了这 “三剑客” 以外，还有三种特殊键帽：热升华、二色和金属。

一般键帽上面的字是印刷上去的，摸上去能感觉到凸起，时间长了会被磨掉。而热升华键帽是直接把染料分子通过加热扩散到 PBT 材料中，这样字符不会被磨掉，但是价格更高。

二色键帽则更进一步，在制作的时候直接使用两色塑料制作键帽，字和键帽直接合为一体。二色键帽价格很高，一套键帽甚至能买一把入门级机械键盘。

金属键帽目前主要通过 3D 打印来制作，国外有专门的 3D 打印公司可以接单。通常流程是找一个键帽图纸，选一种金属，交钱，然后就可以打印了。我之前看过一个价目表，连金银这种贵金属都可以打印，价格嘛大家都懂的，非土豪可以直接跳过。

 灯 有些按键带背光，灯厂（Razer）就是此中翘楚。

* xx 无冲
xx 通常是 6 键，6 键无冲的意思就是同时按下 6 个按键也不会产生冲突。目前的 USB 接口和蓝牙基本都能做到 6 键无冲，如果是 PS/2 接口（就是老式的那种圆口）理论上可以实现全键盘无冲。

* 正刻、同刻、侧刻、无刻
这说的是键帽上字符的印刷方式。正刻就是我们最常见的方式，直接印刷到键帽正面；同刻和正刻类似，区别是同刻是阴刻，字符会凹陷进去；侧刻是把字符印刷到键帽下方，手指敲击的那一面没有字，字在正对你身体的那一面上；无刻就是完全没有字。

* 钢板
大部分机械键盘底部都有钢板，有钢板的键盘会更重、（据说）更稳定、（据说）更牢固、按起来声音更大——按到钢板上了声音能不大嘛。目前来说主流的机械键盘基本只有原厂没有钢板，其他键盘比如 Race 也有无钢板版。

* 104、87、84、82
这三个数字表示键盘上按键的个数，104 键有小键盘，8X 系列没有小键盘，细节上有些差别。没有小键盘的键盘会更紧凑一些，更加方便携带。有时候也会说 60%、75%，同样表示的是按键数量。

* 手托
机械键盘普遍比较高，使用时间太长手腕可能会不舒服，这时可以选择加一个手托。手托有各种材质，比如木制、皮质、塑料等等，通常的选择是木制。不过这个属于进阶物品，一般来说不需要，基本上和灯一样属于炫耀类物品。
* MX-BOARD 2.0C G80-3802机械键盘 黑色 青轴 键帽 ABS
