#+TITLE: 旧事重提，对于当年对阵法学院二队的分析
#+DATE: 2009-08-08 01:35:25 
#+TAGS: 
#+CATEGORY: 
#+LINK: 
#+DESCRIPTION: 
#+LAYOUT : post

#+TITLE:     旧事重提，对于当年对阵法学院二队的分析
#+AUTHOR:    赵骥
#+EMAIL:     zhaoji-001@163.com.cn
#+DATE:      2009-08-08 01:35:25
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  zh_CN
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LATEX_CLASS: ctexart
-----------------

（本来是给老大的新日志的回复，一看长度，都可以成一篇新日志了，还是发出来吧，字大点儿，看起来省劲儿）
 
下面的立论及其他主要思路由焦鹏飞同学准备比赛时提出，本人只负责回忆整理
 
背景资料
- 正方（工物系）大学教育应该更重视科学精神
- 反方（法学院二队）大学教育应该更重视人文精神
 
#+BEGIN_HTML
<!-- TEASER_END-->
#+END_HTML


因为从以往各战例来看，我们的立场绝对的劣势；从双方实力上来说，我们和法学院的师兄师姐绝对不是一个档次上的，如果我们和他们在常见的战场上打，直接是没有商量地被虐。所以我们从开始对立论的共识就是必须出其不意，攻其不备，所有网上的立论都绝不能出现。各战例的思路都是比较二者的重要性，而且常常是讨论科学引导人文还是人文引导科学的问题……显然和法学院扯这些就是主动寻找刺激…… 

于是，我们立论中首先说两者是同等重要的，而且我们还留有余地的说，有些时候人文是比科学精神更重要的，赛前的准备是如果局势不好，就退到这条底线，承认人文精神比科学精神更重要。但是这种重要，是就全社会而言，社会缺乏人文精神并不足以成为大学教育里人文精神比科学精神就更重要的原因。证明这一逻辑不成立原因也有不少，比如我们提到的资源分布，比如人文更依赖社会教育。 

开篇立论做这么大的让步的目的，就是让法学院的学长学姐的一记几乎百分之百会击出的重拳打到棉花上，发不出力道来。事实效果不错，但也使我们形成了一个习惯，不敢于强队在纠结问题、关键问题上硬扛硬拆，容易走偏，在决赛就走偏的太过分了。 

法学院的立论我怀疑好像是从国辩重庆大学的立论里引用了很多，当时听着很耳熟，但现在没有资料，也没有老大这么好的头脑，不敢妄下断言。可以确定的是里面没有太新的东西，毕竟强队打我们这种杂牌儿估计用这些传统的东西就够了。立论的关键是，人文精神在社会上很缺乏，而且人文精神引导科学精神所以很重要，然后大学对社会有很重要的责任，所以我们要在大学教育中强调大学教育。大略印象是这样，如果有偏差，还希望其他当事人来更正。 

攻辩的时候，工物分工呆板的缺点又出现了~~~老焦那个我在场上听着还是很好的。我那一轮儿就问题大了，第一次对阵高水平高语速的辩手，完全掌握不住自己的节奏，思路很混乱，直爽点儿说，可以算是被打残。这场攻辩，从一开始场面上已然差了不少。另外说到社科院的数据？嗯，不太有印象有这么个东西了。我只记得张蔚然学姐提出顾校长的一段话，我当时质疑，“大学生的教育就是大学教育吗？”，然后蔚然学姐说的是这出于某本杂志（是什么忘了），反正好像没太理解我的意思。而且因为时间很紧，好像当时我没把我想说的话说清楚，反正攻辩很烂。后遗症就是我以后看见高语速的学姐心虚，结果决赛又让我对阵刘若昱学姐，气势就不对等，我汗…… 

方向盘和发动机那儿很纠结，我们在场下几个人关于这倒底是谁先提的倒了半天，现在我也想不起是谁提了。但我们的思路是很清楚，两者就算有引导关系，也先要守住同等重要（同等重要时，引导不引导的也就无所谓了）。 

小结的关于马加爵点是我们准备的时候就设计过的，法二的学姐学长们不出所料的把我们熟悉的马加爵，刘海洋等“前辈”请出来了。我们的反驳思路是，一就是人文精神的内涵不是那么低，不是不杀人不放火不伤害小动物就叫有人文精神;二是我更偏向的思路，“三岁见老”，小学、初中，中国那么多义务教育干什么去了？这些东西是你应该从大学才学的东西吗，不能让所有东西都要大学来承担，这是中国教育的失误，但不能是在大学出现问题就说是大学失误，解决的根本不在于大学。 

自由辩论里，许佳鹏和焦鹏飞表现神勇，而我在攻辩之后，大半时间继续萎迷，这场比赛远称不上爆发。法二的学长学姐们，作为一支传统强队，首先打的很传统（现在仍然很怀疑大概是出于轻视吧，从例子到打法都是很传统的）；然后打的很强硬，因为实力高出很多，法二在例子上举的都很极端很强硬，在遣词用语上也很是强势，不给我们留有空间，语言中明显传达出来，他们追求的不是胜势，是完胜，不是6对4，是10对0的虐杀。太过不给我们留余地，也让他们的余地少了很多。举一个例子，个人认为是法二的最大失误。场上后来我们一度纠缠于马加爵，我们就提出了对有和无的争论方式的质疑，然后张蔚然学姐当时说了一句——马加爵并非没有人文精神，他并没有杀曾经送饭给他吃的同学（大意如此）。我感觉其实这很牵强，如果不是追求全胜，完全可以放弃这个阵地，在其他地方完全大有回旋余地，如果这么说，不仅观众听来不易接受，而且还影响了关于人文精神的定义，只要有尊重人的行为就叫有人文精神。于是就出来结辩里那个大概是全场比赛最流氓的一句话，“那是不是根据仁者爱人，您爱您女朋友，您就是仁者了？” 

说结辩吧，潘队长的结辩我没有资本说什么，因为实在印象不清了。我的结辩里有无的那个点前面说过了；终点站确实是对方说的，大意是在社会上不会有这么多资源，所以就是人文教育的最后一站，其实不是太有力；99%不是法学院的学长学姐说的，但是他们说过无论我们把多么多的资源放在人文精神教育上也不为过，完全无视科学精神，于是我就在结辩里提到99%的概念，意欲造成这个效果：我们只不过要求51对49，你们非要99%对1%，是不是太强势了？ 

收尾是我全系列清锋明辩打下来的唯一可称得意之作的发言，其实是预谋已久，主要是对网上所有战例的分析，好像没人提过人文教育有了资源是不是就一切问题迎刃而解，而且这确实可以商讨，于是就额外做了一点儿准备，没想到法学院的学长学姐们竟然这么继承传统，那我就恰好把这些东西用上了。主要是得益于正四永远是最后一个说话的人优势。 

感觉如果说法学院的惜败，除老大的分析外，可能还是“传统”与“强硬”限制住了他们的手脚。更不知天高地厚的说就是，不应该轻视对手，“宣父犹能畏后生，丈夫未能轻年少”，嘿嘿。
* 评论
张云晓Aroma2009-08-08 09:46
看上去很振奋人心，那句所谓流氓的话很是经典啊！师傅确实才思敏捷，实力非凡啊····

赵骥2009-08-08 10:07
回复张云晓@Sun：那句话确实曾被传为经典……说话恶毒的经典，史称“毒舌”。
振奋人心？有很多细节没写清楚，没经历过的你，能看出振奋人心来，实在理解力很不一般。

冯柳青2009-08-08 10:21悄悄话
呵呵～当时就只是在你的结辩的时候进去听了一会儿，就觉得你是我在整个清风明辩进行到那个时候见到的除了我们老大，现场感最强、最有气势的的四辩了～赞一个！

张云晓Aroma2009-08-08 10:28删除 赞 回复
回复赵骥：毕竟看过视频嘛，嘿嘿，很强大·······

赵骥2009-08-08 10:30悄悄话
回复冯柳青：这评价可担当不起，谢谢谬奖。
但这确实是我个人在清风明辩最好的一次结辩，首先面对的不是老大的无敌结辩，心理压力小；其次，心态放松，反正完全做好回家的准备了，老大说我们向死而战，我当时倒没这么悲壮，我想的是——我自横刀向天笑，笑完回家去睡觉……呵呵，一笑。

赵骥2009-08-08 10:38
回复张云晓@Sun：视频没拍到的部分都很惨……
