# -*- mode: Org; org-download-image-dir: "../images"; -*-
#+BEGIN_COMMENT
.. title: 立此存照（这一阶段最后一篇有关辩论文章）
.. slug: li-ci-cun-zhao-zhe-yi-jie-duan-zui-hou-yi-pian-you-guan-bian-lun-wen-zhang
.. date: 2009-05-21 01:22:46 UTC+08:00
.. tags: 人人网, 辩论
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT





因为缺乏创意，只好从鲁迅先生那里借来这个标题，写一点儿真正最终的总结性文字。

因为想找一点儿不足，所以一直想找一点儿他人对比赛的评价，用百度搜了一下，只看到了
某个博客对决赛一句有意义的话,（校学生会的东西几乎没任何意义，鄙视一下）。在校内
四处游荡了两天，学到了不少东西，不过也估计踩得几位学长学姐都烦了。决定自己写点儿
东西，整理一下思路。

还是从决赛说起吧，我认为，这是一场对我们的提高水平最有作用的一战。

那篇博客说“ *场上的唇枪舌剑,针锋相对.不过感觉整个辩论过程中少了一点深度. 他们花了
大量的时间讨论关于结果,预期结果等的区别* ”。评委貌似也说过类似的话。这条评论有道
理吗？有。有意义吗？对我们意义不大。也许我们就是因为这一点输的，但是，这个点太没
有普遍性了，工物绝不是一个没有立论深度的队伍，虽然也许比人文会差一些，（这一点在
决赛中没能比出来，感觉人文的师兄师姐们因为只需要用浅的理论就够了，所以他们的深度
也不是很明显），但是我们也绝不是只在决赛现场表现出来的那点儿深度，至少在准备中我
们有很多的更深一层的东西没有表现出来。这是我们自己的问题，可也是人文师兄师姐张开
的一张八卦阵的精髓，那正是“并敌一向，千里杀将”（《孙子·九地》）。我们被师兄师
姐不知有意还是无意的抛出的一个破绽“预期结果”穷追猛打，而学长学姐们也乐于在此纠
缠，于是我们自已的立论没有得到任何拱卫，在王斌范学长的陈词下几乎不堪一击。当然，
还有一方面责任是我那个水到不能再水的、纯念稿的四辩陈词，没有起到应有的作用，如果
能背一下，也许会比念好很多，当然，与空手陈词的杀伤力相差不知几个正无穷了。

换言之，对于决赛这个例子，抛开技术层面，我们是不是从来没想过打法的思路，如何布阵
不应只是攻防，还应有战略上的东西吧，或者说工物系没有风格，恐怕也就是如此，我们知
道要寸土必争，可具体怎么争，我们没有太成体系的东西。许佳鹏同学说过“乌合之众”恐
怕也是考虑到这一方面。

决赛就写这么多吧，下面开始全面的回顾了。

主要写人吧，除我以外的六名辩手。因为不只是表达感激，所以有可能会提一点儿小缺点，
希望大家以眼还眼以牙还牙，也说说我的缺点。（除老焦外，排名主要以上场次数为准，大
家应该都同意吧）

从老焦开始吧，文静沉稳，典型的儒辩风范。场上的表现有目共睹，四两拨千斤的功力，让
我这种纯刁蛮之人很是汗颜，但却只是冰山一角，场下的作用方显一代不凡风骨。每次讨论，
学识渊博、眼光独到的特点都表露无疑。很多次，我说最佳辩手不应该是我拿，正是因为老
焦，（又要开始大段引用了，文思枯竭的表现）“见胜不不过众人之所知，非善之善者也；
战胜而天下曰善，非善之善者也。故举秋毫不为多力，见日月不为明目，闻雷霆不为聪耳。
古之所谓善战者，胜于易胜者也。故善战者之胜也，无智名，无勇功。故其战胜不忒。不忒
者，其所措必胜，胜已败者也。”（《孙子·势篇》）开战之前，已形成之“势”极有利于
我，极不利于敌，对比悬殊，故其场上的作用如见日闻雷，人不称其善，只认为被战胜一方
本不堪一击。因此老焦“无智名，无勇功”，但我们知道，什么才是王者之风。

然后，两位一辩同学许佳鹏，陈偲。还是要说气质真的很重要，也许这两个人在语言或逻辑上与老焦比有一定差距，但是这两个人在场上的作用从来不可取代，因为没有其他人来取代他们这种比较亲和，比较能让台下观众接受已方观点的台风（无论是不是装的，呵呵）。两个人，陈偲比较适合守立论，许佳鹏比较适合进攻，（用你自已的话说“冲出去扔雷”，呵呵）但是还是因为全队没有明确的风格，其实导致你们两人的风格都没能最大发挥。（当然这不是某一个人的责任，老焦，你千万别再说因为你设计的打法导致的这种情况之类的话啊，那我可就有罪了）

两位二辩，余韵寒和陈鑫儒。余同学的优点被评委夸过了，我也就没什么需要多说的了。而鑫儒是语调很柔很快，很像太极，但又有出其不意，剑走偏锋的特点。两人其实也是不同风格，余韵寒是思路很正统，但提出问题的速度极快，一个问题扔出去，无论对方如何回答，总会有接连不断，绵延不绝的问题冲出去。而鑫儒的问题以诡异为主，一时之间，对方难以回应，尤其是类比归谬运用的很独特，很有杀伤力。

还剩下我们强有力的系决赛的核八一四辩了，因为刘勇的好多方面和我一样，太多进攻，却急于进攻时容易让自已的思路有些错乱，辞不达意，一时语塞都会有，所以，当局者迷，我说不出太多中肯的意见。

次要的，写一下自已的几场四辩陈词的总结。自认为，最好的一次四辩陈词在于第三场打法学院，主要得益于，以牙还牙，用法学队长常用的“辩论不是为辩而辩，在这里我想分享一下我们对这个辩题的思考”的句式，把最后一支箭射了出去。然后，极其惭愧的是第二好的是第一场打电机，虽然不入流，虽然连升华抒情都没有，但是，至少是现场攻击做的不错，立的方面是临场的反应，不是念稿。排第三的是半决赛与决赛，念稿成为了最后的常态，驳完了以后，就成了纯朗诵……尤其是半决赛，语速太快，以至于没人能听懂，我汗死……在任仕廷与王斌范两位学长的强大反衬下，我的陈词几乎什么都不是……至于打软院的那场，我就什么都不说了，四辩陈词烂到不行了。

所有的东西，也算有了一个收尾，今后我可能不会再这么用心去想这些东西。再打开这篇日志，回忆这种心情，可能就是明年送给九字班孩子们的一份礼物了。

* 评论
#+BEGIN_EXAMPLE
王斌范2009-05-21 08:42删除 赞 回复
最近演出和艺术团其他事务太忙，日志创作放缓，到写到后面的时候我会提出对你们队的印象，以及对三年来我见过的比较突出的辩手的评价，其中肯定也有你……
你给我印象最深的确是对潘文韬的那个结辩，当中看到了很多即兴的因素，而且说理很是清晰。潘文韬不是太好的结辩，只不过经验丰富一点而已，但是我本以为工物如果不能在结辩前拿下比赛，最后还是会很危险。听完两个结辩之后，我感觉你们大概能赢了～可以好好回忆一下那场的感觉，离空手可能还有距离，但是已经挺不错了～
另外，不要再用“我想分享一下我们对这个辩题的思考”这句话了……这句话是我在去年清锋明辩开幕赛上首次使用的，至今认为重复用这句话的人都没有理解当初我这样说话的涵义……以你的水平，还是应该去创造只有你能说出来的话，不必对前人的东西亦步亦趋～（当然当时你不知道这个典故了，亦步亦趋的是对方）

杨一凡2009-05-21 10:52
........

闫盛枫2009-05-21 12:19
这届的清锋明辩我看了除了第一场小组赛以外的所有比赛，除了人文一队的同学们，对你的印象最深，思维很敏捷，常常让人拍案叫绝，也正是你们这些辩手一直吸引我看完清锋明辩每一场比赛，你想听建议，O(∩_∩)O~我倒是有点，觉得你在辩论技巧和辩论系统性的训练上和他们还有差距，应该是是八字班的原因吧，如果你要继续辩论的路的话，我觉得在这方面稍微努力下的话你就perfect了~O(∩_∩)O~个人拙见~

赵骥2009-05-22 10:44
回复王斌范:真是相当期待最新日志啊……
对潘文韬学长的那一场，因为我在攻辩和自由辩论时表现都不好，自由辩论最后一分钟我就几乎放弃了，准备在总结陈词时好好表现，可能是因为准备的比较用心吧，结辩相较其他四场做的要好一些。能力所限，总是厚此薄彼，自由辩论做好了，陈词就没有太多现场感了。做为新辩手，我还是很欠火候。

赵骥2009-05-25 00:09
回复闫菜菜:我也是这种感觉，自已很业余、很山寨。以后如果有机会与校会厚颜混迹的话，可能会变的专业点儿……现在是纯不按套路出牌
#+END_EXAMPLE
