#+TITLE: org mode 常用技巧
#+DATE: 2016-11-30 16:13:58 
#+TAGS: 
#+CATEGORY: 
#+LINK: 
#+DESCRIPTION: 
#+LAYOUT : post

#+HTML: <!--TEASER_END-->
* 截图 =SPC m i s=

设置截图保存路径

https://github.com/abo-abo/org-download

They are: org-download-method:

    -*- mode: Org; org-download-image-dir: "~/Pictures/foo"; -*-

To set it for all files at once, use this:

    (setq-default org-download-image-dir "~/Pictures/foo")
second part is:

org-download-heading-lvl is nil => ""
org-download-heading-lvl is n => the name of current heading with level n.

Level count starts with 0, i.e. * is 0, ** is 1, *** is 2 etc. org-download-heading-lvl becomes buffer-local when set, so each file can customize this value, e.g with:

    -*- mode: Org; org-download-heading-lvl: nil; -*-
org-download-timestamp: optionally add a timestamp to the file name.

Customize org-download-backend to choose between url-retrieve (the default) or wget or curl.
* 粘贴图片 =SPC m i y=
* 跳回原点 =C－o=
  If you are using evil then C-o should always get you back to your last position.
* latex 
** 输出时，只要\begin{document} \end{document}
 使用 body only 命令  =SPC m e C-b=
* 增加 file-local variables (through SPC f v f).
* 如何能够 make -j4 
=C-u 4 SPC c c=
* local Variable
#+BEGIN_SRC org
# Local variables:
# mode: Org; 
# org-download-image-dir: "../../figures"; 
# org-download-heading-lvl: nil;
# eval: (defun zhaoji/org-save-and-export ()  (interactive) (if (eq major-mode 'org-mode) (org-latex-export-to-latex nil nil nil t))); 
# eval: (add-hook 'after-save-hook 'zhaoji/org-save-and-export nil t);
如果没有这个 最后的 nil 和 t 那就会是全局的设定了
# end: 
#+END_SRC
