# -*- mode: Org; org-download-image-dir: "../images"; -*-
#+BEGIN_COMMENT
.. title: 配置 Manjaro 纪录
.. slug: pei-zhi-manjaro-ji-lu
.. date: 2017-01-22 14:08:43 UTC+08:00
.. tags: 
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT
* Manjaro 优点
“虽然装的是16.06预览版，但是非常稳定，没有ubuntu和openSuSE在我本子上的闪屏bug，
也没有其他莫名其妙的bug。驱动完善，设置里一键就安装好了。中文支持也非常好，字体
好看和ubuntu不相上下，konsole里默认配置也不会出现中文显示不全的bug（号称稳定、
kde支持最好的openSuSE都有这个问题），chrome里中文字体也不虚，无需配置。aur里只要
你想要的软件都有，什么搜狗、wineqq-intl、微信，FeelUOwn，ss-qt5（这貌似是arch的
优点），直接一条命令就装上了，笑看其他发行版找PPA找源找二进制包。真是太好用了，
为什么国内用户这么少呢，感觉是很有前途的发行版，我要传教！”


* 配置
编辑 /etc/pacman.d/mirrorlist， 在文件的最顶端添加： Server = https://mirrors.tuna.tsinghua.edu.cn/archlinux/$repo/os/$arch

更新软件包缓存： sudo pacman -Syy
* docker
** Installation
 For the normal package a simple

 =$ sudo pacman -S docker=

 is all that is needed.
rtu
 For the AUR package execute:

 =$ yaourt -S docker-git=

 The instructions here assume yaourt is installed. See Arch User Repository for information on building and installing packages from the AUR if you have not done so before.
** Starting Docker
 There is a systemd service unit created for docker. To start the docker service:

 =$ sudo systemctl start docker=

 To start on system boot:

 =$ sudo systemctl enable docker=
