# -*- mode: Org; org-download-image-dir: "../images"; -*-
#+TITLE: 霜高风定独凭栏——苏樱《王国维点评<红楼梦>》
#+DATE: 2013-09-08 22:29 
#+TAGS: 人人网
#+CATEGORY: 
#+LINK: 
#+DESCRIPTION: 
#+LAYOUT : post
#+OPTIONS: toc:nil
-----------------
#+BEGIN_QUOTE
不管你的设定多么宏大深邃，蓝图多么吞天吐日，他们永远只看到情情爱爱，“二女争夫”。这种角度下看，爱情，“天下多少大事，就坏在了这些东西的手里”。
#+END_QUOTE
#+HTML:<p align="right"> ——题记 </p>


* 一

中国人能把所有节日过成情人节，能把绝大多数电视剧拍成一种类型——爱情片。不管是女侠、警花、女教师、女护士，女主角最主要的作用永远都是谈恋爱。爱情在任何一种类型片里喧宾夺主，这就是市场需求。
-----------------

古人说，“十部传奇九相思”。我更愿意相信，非此题材的，不是没有，而是卖不出去，失传了。  

我们都骂高鹗的续书把红楼梦引入了“钗黛争婚”这么庸俗的一个悲剧，但要是真以“白茫茫大地真干净”结尾，我们今天能不能看到这本书都是个问题。

-----------------
去网上一看，人们津津乐道贾宝玉同学的“小伙伴”，我们列个单子： 

袭人、麝月、秦钟、蒋玉菡，这些多多少少有点儿吧，还ok；黛玉、宝钗、湘云、晴雯，YY一下未尝不可；北静王，呃。。。


是，我没有写错，北静王，你们感受一下。。。

这种敢于认为，一切结交的目的都是勾搭，任何行为的动机都是荷尔蒙，所有（异性）朋友的归宿都是炮友的大无畏精神，深深震惊了我。 
---------------------------

震惊了多年后，我才慢慢开始接受，确实有些人，“千红一哭”，“万艳同悲”，“花落水流红”这种大悲剧大框架，影响不到他们。他们用潜在追求者的视角，审视着一切（异性）关系。

眼见天下之大，只见情情爱爱，“用了这许多好材料，难道竟不过老是演一出轮回把戏而已么”。这样的眼光看世界，久了，真不会觉得无聊吗？ 

所以这次介绍这本书的目的，是如果有人厌倦了那种三姑六婆的八卦视角的话，这里有一双王国维自叔本华处借来的哲学与文艺评论的眼睛。苏缨在前言里说的话，我原样照抄过来：
#+BEGIN_QUOTE
我很想说“红学本应是这个样子”，但面对今天的时代气氛，这句话看来要改成“红学竟然可以是这个样子”。 
#+END_QUOTE

* 二
老子说：吾所以有大患者，为吾有身，及吾无身，吾有何患。
---------------------------

人生于世，便有欲望，这是烙在每个人基因里的原罪。
#+BEGIN_VERSE
      欲望得不到满足，便是痛苦；
      欲望全得到满足，便会无聊。 
#+END_VERSE
人，在痛苦与无聊间如钟摆般切换，这便是叔本华的“钟摆理论”。

欲望、生活、痛苦，三位一体。

叔本华认为：每一次欲望的满足，都像是丢给乞丐的一丁点儿施舍，在今天维系了这个乞丐的生命，为的是在明天延长他的痛苦。

---------------------------
我们有寻到幸福的可能吗？
---------------------------

王国维写过一首《浣溪沙》，下阙如是， =“隔座听歌人似玉，六街归骑月如霜。客中行乐只寻常。”=

前两句美不美？可惜，都是别人的。

强加延伸的话，人生天地逆旅之间： \\
今日相亲，明日相仇；今日把盏言欢，明日形同陌路。爱别离，怨憎会，求不得，：）。

客中行乐，终归不是家园。
---------------------------

不过，正是这样一颗飘泊作客之心，看到这个世界美丽的瞬间。
因为这个时候，你与这个世界产生了审美的距离。这一刻，你与世界没有利益的关系，索求的欲望，所以你从叔本华的钟摆中短暂跳脱出来。
见山是山，见水是水，了然无挂碍于胸。佛家管这个叫成佛，王国维称之为“审美”。

---------------------------
简介到这儿，如果有兴趣，就到书里去寻求更细节的答案吧。

* 三
      本书文笔细腻但不拖泥带水，截取两段。（苏缨总算不需要为了满足出版社要求，生硬的唧唧歪歪了，最早的几本，我们这些旁观者看的都累）
#+BEGIN_QUOTE
一个人在悲哀的境遇中自然很容易陷入悲哀的情绪，而在欢乐的顶点有时候竟也会生出一种刻骨的悲凉，这种悲凉比之前者往往深刻许多，因为它摆脱了切身的利害，而指向了人生的终极。
      ……
　　于是最美好的事物反而变成了最令人悲伤的，因为我们会晓得，今天有多爱，明天就有多痛。于是我们甚至会生出这样的质疑：命运之所以在今天眷顾我们，就是为了在明天抛弃我们，它之所以给了我们那么多美好的事物，就是为了看我们如何失去它们。”
#+END_QUOTE
      
#+BEGIN_QUOTE
“世人常道，这件事若能这般这般，这次意外若能如何如何，该多好；将来若能怎样怎样，我必将如何如何。凡“若”字出现，皆是因为已对某人某事无能为力。这个字，是失意者的自欺欺人，不是将幸福寄托在老朽腐烂、灰飞烟灭的过去，就是期望于深不可测、形迹可疑的未来。当现实无可挽回，任何行动均属浪费，只能在语言中实现憧憬，但无论你的话在语言逻辑上如何天衣无缝，现实总是用超越逻辑的方式证明给你看它有多残酷。（这段其实是作者自引的《纳兰容若词传》）
      人生若只如初见。
      若没有遗憾，一生不必说“若”；而说再多的“若”，却无法不遗憾。”
#+END_QUOTE

---------------------------
#+BEGIN_QUOTE
#+BEGIN_CENTER
今宵便有随风梦，知在红楼第几层。 
#+END_CENTER
#+HTML:<p align="right"> ——纳兰性德《饮水诗集·别意之三》 </p> 
#+END_QUOTE
（后记：这是一篇非典型读书札记，讲个红学的故事，讲故事全系列第五。向读书会简介一下近期读完觉得不错的书，反正估计也没什么人看，就按我自己的口味，先从熊逸和苏缨的书开始吧）


