# -*- mode: Org; org-download-image-dir: "../images"; -*-
#+TITLE: 我的清锋明辩反思录（3） ——辩风和立论之立论
#+DATE: 2010-01-31 02:27:00 
#+TAGS: 
#+CATEGORY: 
#+LINK: 
#+DESCRIPTION: 
#+LAYOUT : post


第二章 辩风和立论(2)——立论
---------------------------------------------------------------
立论的好多的问题，从风格里就有答案了，优点是我们的立论重攻防重实用，重内在逻辑自恰（不自恰就被拆），但缺点是可能太“难听”，比如说我们的立论里对价值的论述可能会很少，没有看问题的高度。此外，还有一个缺点，我们立论有很多是散点，为补洞加进来的，使得有些立论体系性不强。

我想强调的是，我认为最重要的东西，是我们立论的时候一直要求的出新点，出新思路，而且是出人意料的惊艳之新。我结辩的最后一部分，其实也一直是这样的东西，全场的比赛的最后，提出一个没人提过想过的东西，这不是升华，但很有效果。

因为我在想，观众来看辩论的目的是什么？很多人不是关心输赢。而且显然和在街上看泼妇吵架的心态肯定不一样，他们希望看到的是台上的人对辩题的理解与思路的交锋，看到一些引起他们思考的东西，他们希望看到对自己有用的东西。辩手追求的是什么的，输赢之外，是说服，说服评委与观众，说服观众，辩手的目的在于让他们产生共鸣。需要的是独特深刻的思考。所以我在想在辩论场上，真正评判的标准是什么？辩论场上不可能有一方打白旗，也很少会有比赛一方有压倒性优势。当没有压倒性优势时，评委看什么，我们看什么来决定胜负，是对这个辩题的思考双方谁更深入，观察角度更高，更何况思维的高度决定你语言的高度，压制性局面背后也常常是思维的差距。（当然泼妇悍夫把淑女文人骂哭的可能性不是没有，但太少了，清华更不可能会有）

所以在立论里、在结辩最后，给出一个独特新颖的思考就是展示给其他人我的思考比对方深入，我的思维高度在对方之上，或者说境界在对方之上。（自王国维后境界有太多含义了，呵呵）

我一直认为，辩论是君子之争，在输赢之外，还有更高的东西，不然不会有这么多人为之痴狂，太功利化会毁了某些东西，比如灵性。双方追求的应是思维的高度，评判只是这个较量的客观衡量者。

如果这个理解没问题，我们就会发现，重攻防绝对不是一支队伍的终级目的，如果以层次分，攻防层次应该是最低的，当然很重要，它是思维高度较量的体现者，但也只是体现，然后是立论层次，这是对辩题的理解，是思维高度的依附者，这应该是一支队伍的重点，我不是为赢而攻防，为攻防而作立论；而为守卫思维而立论，而攻防。（予岂好辩哉，余不得已也，呵呵）。在立论层次以上感觉应该还有一层，但我不知道是什么。
 
---------------------------------------------------------------
听着感觉对实际不会有太大影响，是不是？我们到实际应用里看看吧，看看立论思路会不会太大不同。（以下全是我闭门造车造出来的，不成熟，还希望有人补充）
 
清华打的辩题绝大多数是价值型辩题，我们五场比赛，除第二场是政策性辩题，其它全是价值型辩题。就我所看的比赛，除人文的半决赛算是事实辩题，其它也全是价值型辩题。我们不妨从价值型辩题入手。

价值性辩题有效词汇可以分为三个层次，攻防层次、立论层次、境界层次（又故弄玄虚了）。“重要”，“利弊”，攻防全是围绕这些词汇展开的，但这些词汇本身没什么好玩的地方。立论层次，正反辩题中不同的部分，立论阐明的东西全都围绕这个中心词汇。境界层次，双方辩题相同部分里的一些名词，这些名词，有些很明显，不用说，有些则容易被我们认为成自明的，不用解释，然而就是在这些潜意识的定义中，高下立判。

比如说01年国辩“信息传播发展会打击本土文化”里的“打击”与否表现的还是价值，是损是益，这就是攻防层次，信息传播发展是立论的基石，是立论层次，而文化就是境界层次，马来亚大学讲“文化的核心是一种价值观”虽然在辩势上没有太大影响，但在逻辑体系上讲很重要。当然这个辩题不打文化基本上是脑残，

然而，以我们自己的决赛辩题为例“人的自我实现过程比结果更重要”，重要肯定是攻防层次名词，过程与结果，或者说“自我实现过程”和“自我实现结果”是立论层次名词，而“人”是境界名词。

为了证明这个名词是被不可饶恕地忽略了的，我问大家三个问题：
1. 人的定义是什么？或者说什么是人？
2. 人的自我实现的目标是什么？
3. 人的自我实现的评价体系是什么？

这三个问题，2由1的答案决定，人的自我实现，是实现人的定义所规定的特征，3由2决定，评价体系好坏在于能否正确判断人的自我实现的目标完成程度。而问题3就包括我们的辩题，（当然还包括评价视角，是个人本位还是社会本位，那个等以后再说）

人文给出了答案，人是理性人（他们的论证中属于工具理性人），自我实现，人与社会价值的统一，评价体系，社会+结果。

而我们因为境界的问题，立论是散点主要应付攻防，思维高度上有弱点，所以只能苍白的用“人之为人的价值”反驳，可人之为人的价值是什么，我们也不知道。为什么在场上一直梳理不出自己的理论体系，一直感觉控场特别乱，就是因为我们理论推演的基础是这样的空。

像这样的想下去，另一套立论思路基本上快出来了，但为了给第七章留点儿素材先不写了。我打完决赛认为输在经验上，后来认为输在立论上，现在认为输在境界上，七分境界，二分立论，一分经验吧。
