#+BEGIN_COMMENT
.. title: 写个京剧的故事
.. slug: xie-ge-jing-ju-de-gu-shi
.. date: 2013-10-10 02:37:46 UTC+08:00
.. tags: 人人网, 故事
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT



#+BEGIN_QUOTE
十五年屈辱俱受尽，佯装笑脸对奸臣。

晋国中上下的人谈论，都道我、老程婴，

贪图那富贵与赏金，卖友求荣，

害死了孤儿，是一个不义之人。

——《赵氏孤儿》程婴
#+END_QUOTE

人生如此艰难，我居然没有认真地讲过一个悲剧，所以选中了《赵氏孤儿》。没看过并仍想读下去的人，（真的有吗？）那剧情请见文末附三吧。
--------------------------------------------------------

我不打算讲一个忠而见疑，信而被谤的故事。

相反，我打算讲讲问什么文首那段唱词，其实不够悲剧。

或者说，那是个剧作者太一厢情愿下的悲剧。

* 一
因为现实根本不可能有“十五年屈辱”。

这个社会有那么好记性吗？你还记得你上上次义愤填膺时，那个事件的当事人吗？

十五年，谁TM还记得十五年前发生过什么？

不，我说不存在屈辱，不是说他们原谅你，更不是还你清白。

他们只是忘了。

如果你能让他们想起你，他们还是像之前那么看你。

但，他们只是忘了。

* 二
不好意思，程婴，“晋国中上下的人谈论”是你的幻觉。

但是我相信，十五年感受是真的。

因为只有你，只有你还记得这一切，在乎这一切。

所以，在这十五年的剧本中，人物只有你一个。

--------------------------------------------------------
有没有人读过柳文扬的《一日囚》呢？

那个生命被囚禁在一天中的人，那个每到十二点就会被神秘力量拉回零点的人。

这种经历就有这种魔力。

在某个夜深人静的孤寂漆黑中，痛苦会把你拖回那个时刻，折磨的你难以入眠。

--------------------------------------------------------
或者，玩过《古剑奇谭》吗？

“岁月如长河无尽，沧海也变成桑田，或许只有我，独自遗落在时间罅隙，永无归途…”

时间在流淌，人们都在往前走，唯独你被遗忘在时间的罅缝中…

--------------------------------------------------------
有些版本的赵氏孤儿里，程婴见孤儿大仇得报，接下来做的是：自杀去见地下的公孙杵臼了。

程婴把人生的意义都寄托在这件事上了，我更接受这个版本。

这才是程婴真正的悲剧，你的视野变狭隘，生命被局限，时间被停滞，在痛苦中循环轮回，成为了生命的全部。

* 三
为什么你要这么在乎这些，如果你看开了，也许剧情会不一样？

你看，屠岸贾比程婴坏多了，骂名强多了，但他活的很好啊？

因为，屠岸贾不在乎啊。

--------------------------------------------------------
但是程婴可能不在乎吗？

他是程婴啊。

如果不是对信义的坚信，他怎么会舍子救孤，卷入这个故事呢？

--------------------------------------------------------
那些观众错了吗？

“法场上的人都来叫骂”，这应该是一个我们期待的热情且高尚的社会吧。

我们完全无权指责他们。

--------------------------------------------------------
程婴比屠岸贾更痛苦。

因为能感受到道德审判痛苦的人，需要有道德。

真正的悲剧背后总有人世的荒谬。

没有人做错，悲剧不是例外，而几乎是必然的。我想叔本华会很喜欢这个故事（见附四）

这是社会的悲剧。

* 四
中国没有纯粹的悲剧，《赵氏孤儿》也是，所以，作者总会让孤儿报仇成功，程婴沉冤得雪。

抱歉，程婴，这些也只能是一厢情愿。

假设这个爆炸性的新闻，又让人们还记得你的事情吧。

你觉得以你一个罪人和背叛者的身份，你讲述的那个真相，孤儿和人们会相信吗？

--------------------------------------------------------
一个正常人，如何在精神病院证明自己是正常人…

一个“人渣”，如何向人们证明自己所作所为无愧于心中道德…

一个罪人，如何向人们证明自己是“敌人心脏中的尖刀”…

而不被怀疑是狡辩与诡诈？

抱歉，你的信用被质疑，你的发言被认为是立场性的。

自证无效，谢谢。

--------------------------------------------------------
如果我们寄希望于历史呢？

我浅薄的历史知识告诉我，相对于《赵氏孤儿》那么高尚的历史童话，历史书上遍布的解读是：

分赃不均，杀心陡起。

--------------------------------------------------------
戏台上，可以有程婴，因为我们能看到你的心理活动。

而现实，无论近观远观，我们作为人，只能采取最稳妥的解读方式，请原谅我们的局限。

这大概可以叫，历史的悲剧。

* 五
其实我不只想讲一个悲剧，这可以是一组悲剧。

+ 如果把二和四组合起来，痛苦的轮回和理解的天堑，那就是《弗兰肯斯坦》的悲剧。（见附五）

  * 一切悲剧都源于，弗兰肯斯坦对人造生物的不信任，而都归向于费兰肯斯坦的自我谴责。

+ 如果把三独立出来，时代的荒谬，那就是《堂吉诃德》的悲剧。（见附六）

  - 《堂吉诃德》的笑点在哪里？
    + 骑士精神吗？那些传统的道德，不是人们最为称赞的吗？
    + 不合时宜吗？那“知其不可而为之”，为何又会被推崇呢？
+ 如果把四独立出来，如何自证无罪，那就是…（假期读的书用完了怎么办）…好吧，我的故事。
  - 这句是搞笑用的。

* 六
文章已经可以结尾了。

不过还是照应一下前文。

柳公子写《一日囚》的时候，想告诉我们，时间的囚徒比空间更可怕。

极尽了时间的囚徒忍受的痛苦。

但为什么没有写到死呢。这种力量不能使你到达明天，但可以使你不再痛苦。

我想说的是，如果你不幸如程婴般执着，那抱歉，也许遗忘，对你是唯一的救赎。

* 附

** 附一：
 知道题目有京剧两个字，肯定没什么人会看。
 但还是在发之前写了上一篇日志，只是为了掩盖这篇日志里浓重的负能量

** 附二：
 如果会有参加了培训的辩手看到这里的话，这个可以作为第一次培训的资料篇。（但愿我其它的朋友们，不会只从这看。）

 这是个传统的资料，有传统的理解——仁人自我牺牲，面对社会误解，使社会正义彰显，本戏宏扬社会正气。

 但可以从四个角度把材料重新解读：

 1. 事实，对应一，彰显，拜托，社会不在乎
 2. 事实解读，对应四，正义，拜托，你为什么这么肯定，人们会这么理解吗。
 3. 身份，对应二，宏扬，拜托，是你的身份，你的视角，你的自我要求，导致了悲剧，还会有人想这么做吗？
 4. 能力，对应三，误解，拜托，误解是可以改正的，我们的社会，只能用谴责伤害有道德的人，它只有这个荒谬的能力。

 所以，这个剧告诉我们的根本不是什么正义战胜邪恶，号召我们向程婴同志学习。

 其实，文章可以找出很多论点，比如四就可以理解为“不要追求高于人们理解范围的道德”。用以反驳，我在培训最后提到的“人可以追求高于一般人理解的道德，如动物保护主义”。

 重要的是，这是个新资料，哈哈。

** 附三：
 故事讲述了春秋时期晋国一场残酷的宦海之争。晋国大将屠岸贾为了权力，害死忠臣赵盾，赵家三百多口除赵氏孤儿被程婴设计救出外，全部被杀。为保全赵氏孤儿，程婴自己的亲生骨肉被残害，而赵氏孤儿也被屠岸贾收为养子，和程婴一起生活在贾府。20年后，赵氏孤儿长大成人，练就一身武艺，得知自己的凄苦身世后，擒杀屠岸贾，为赵家报仇雪恨，为国家铲除一大祸害。                                                               
 ——百度百科

** 附四：
 叔本华把悲剧分为三种状况,，第一种是由异乎寻常的恶人造就的悲剧，第二种是起于盲目的命运和偶然的机运，第三种是剧中人不同的地位和相互关系造成的悲剧。

 在叔本华看来第三种悲剧最好，因为这种悲剧“既不需要有一个巨大的谬误，或者闻所未闻的偶然事件，也不需要一种人物，其邪恶达到了人类所能达到的极限；而只是些具有普通品德的人物，在普通的环境中，彼此处于对立的地位…而他们当中没有一方是完全错误的”。他认为第三种悲剧正足以显示“不幸”乃人生所固有，即人生即苦痛，悲剧的本质就在于显示宇宙和人生的本质。…普通的人与人之间种种复杂的社会关系所产生的结果，这样才是最具悲剧美的。

** 附五：
 主人公弗兰肯斯坦是一位从事人的生命科学研究的学者，他力图用人工创造出生命。在他的实验室里，通过无数次的探索，他创造了一个面目可憎，奇丑无比的怪物。开始时，这人造的怪物秉性善良，对人充满了善意和感恩之情。他要求他的创造者和人们给予他人生的种种权利，甚至要求为他创造一个配偶。但是，当他处处受到他的创造者和人们的嫌恶和岐视时，他感到非常痛苦。他憎恨一切，他想毁灭一切。他杀害了弗兰肯斯坦的弟弟威廉，他又谋害弗兰肯斯坦的未婚妻伊丽莎白。弗兰肯斯坦怀着满腔怒火追捕他所创造的恶魔般的怪物。最后，在搏斗中，弗兰肯斯坦去世，怪物很懊悔，最后跳海自杀。
 ——百度百科 
** 附六：
 本书是西班牙大师塞万提斯划时代的巨著，是文艺复兴时期的现实主义巨作，也是世界文学史上一颗璀璨的明珠。主人公堂吉诃德一方面脱离现实，爱幻想，企图仿效游侠骑士的生活；另一方面又心地善良，立志铲除人间邪恶。是一个可笑、可叹、可悲又可敬的人物，是幽默文学中一个不朽的典型。
 ——百度百科

* 评论
#+BEGIN_EXAMPLE
郑翔宇Amadeus2013-10-10 08:41删除 赞 回复
想说的太多，还是不说了。点个赞吧。

赵骥2013-10-10 09:55
回复郑翔宇Amadeus:话说，我发现这是我写的最长的一篇日志…

郑翔宇Amadeus2013-10-10 12:08
回复赵骥:因为有很长的附！还是百度百科的！

赵骥2013-10-10 12:13
回复郑翔宇Amadeus: 我前面写的也不短…其实附录部分没啥劲…我觉得这篇写的还算不错…你想说啥啊之前，求留言可爱

郑翔宇Amadeus2013-10-10 12:19
回复赵骥:还没整理好，大概是自恋狂被揭穿后的balabala？

赵骥2013-10-10 12:21
回复郑翔宇Amadeus: 哈哈，期待一下bulabula的部分

李世民2013-10-10 15:17
表示很喜欢 二最后那部分，赵氏孤儿小时候查成语的时候大概了解过，感觉程婴最后自杀时特别伟大，现在反思一下，但对于程婴来说不一定不好，历史上狡兔死走狗烹的事情也是很多的
#+END_EXAMPLE
