# -*- mode: Org; org-download-image-dir: "../images"; -*-
#+BEGIN_COMMENT
.. title: 写个儒家的故事之二
.. slug: xie-ge-ru-jia-de-gu-shi-zhi-er
.. date: 2013-08-16 12:44 UTC+08:00
.. tags: 人人网, 读书, 故事
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT

#+BEGIN_QUOTE
       我播下的是龙种，收获的却是跳蚤 
#+HTML:<p align="right"> ——海涅 </p>
#+END_QUOTE 

这种没人看的日志，吐槽就可以更恶毒一点。

上一篇讲被世俗化的宗教，这一篇用儒家的“忠”做例子，讲讲被大一统政治阉割过的学术。

小时候看《宰相刘罗锅》，印象极深刻的一句话就是“君叫臣死，臣不得不死，父叫子亡，子不得不亡。”据说这就是儒家的忠孝二字。

大一点儿了，就读到“忠臣不事二君，烈女不更二夫”等等理学名言。

---------------------------

等到读书的时候发现，嗯…为啥孔孟的书里找不到这些东西

先说”贰臣“这件事情。

孟子游说魏、齐、滕、宋诸国，（孔子周游列国其实也差不多）见了君主都是极力宣传尊礼行仁，一扫天下的主张。特别是孟子，全然一幅”只要你恢复礼乐，力行仁政，我就帮你扫平天下“，这里面被扫平的呢，包括他的旧日老板，也包括孟子的”祖国“╮(╯_╰)╭（真排起来，邹国和鲁国才是他的父母之邦）

举个直接点儿的文本，《孟子·梁惠王下》：

#+BEGIN_QUOTE
齐宣王问曰："人皆谓我毁明堂。毁诸？已乎？" 

孟子对曰："夫明堂者，王者之堂也。王欲行王政，则勿毁之矣。" 
#+END_QUOTE

齐宣王说，周天子东巡接见诸侯时留下的明堂，在我这儿占地方，别人都劝我拆了，孟先生你怎么看？

孟子说，明堂是天下王者之堂，如果王能行王政，那就别拆了。

换言之，你就留下自己用呗。搁在大一统时代，这就是公然鼓吹谋朝篡位。



孟子的逻辑比后世那些专心搞权谋的伪儒实在太多了：推仁心，行王政，不管你什么血统什么政权，你当天子我都支持。

很可爱的逻辑，但在后世，这话就没听起来这么顺畅了。

假设宋金交战，现在金主真心行仁政，宋朝儒生去给金主出谋划策，宋朝子民箪食壶浆以迎王师…

这事儿，总有点儿无法想象。

---------------------------

再谈谈”君叫臣死“。

举个很多人知道的例子，安史之乱，张巡和许远守睢阳，孤城粮绝，食人三万。

大文豪韩愈，文起八代之衰的韩子韩圣人，写《张中丞传后序》，说当时内无粮草、外无救兵，"所欲忠者，国与主耳"，吃人也是应该的。

我不知道孟子对此事会怎么看，但我知道孟子讲”率兽食人“，愤恨之色，英气逼人
#+BEGIN_QUOTE
庖有肥肉，廄有肥马，民有饥色，野有饿莩，此率兽而食人也，兽相食，且人恶之，为民父母行政，不免于率兽而食人，恶在其为民父母也？
#+HTML:<p align="right"> ——《孟子·梁惠王上》 </p>
#+END_QUOTE 

那么，直接吃人的，是些什么玩意儿？

-----------------------------------

说了忠，不妨说说孝，《二十四孝》还是很有名的吧，郭巨埋儿也应该有很多人听说过：

#+BEGIN_QUOTE
郭巨，家贫。有子三岁，母尝减食与之。巨谓妻曰：“贫乏不能供母，子又分母之食，盍埋此子？儿可再有，母不可复得。”妻不敢违。巨遂掘坑三尺余，忽见黄金一釜，上云：“天赐孝子郭巨，官不得取，民不得夺。” 
#+END_QUOTE

这应该是个喜剧结尾吧？但大概所有人都会想到一个问题，如果没有那釜金子，剧情的走向会是？

-----------------------------------

在这两个故事里，忠要吃人，孝要杀人，这里没什么使用任何比喻夸张的修辞手法。


（一个有”意思“的事情是，在忠孝这些道德标准如此拔高的同时，中国的汉奸数量也是出人意料的多。

《明朝那些事儿》讲过明代的倭寇之患，在“倭寇”人员的构成上，倒是汉人占到了相当大的比例。

再比如清军屠杀的“扬州十日”，
#+BEGIN_QUOTE
在通常概而述之的历史记载里，攻打扬州的是豫王多铎所统率的清军，而事实上，仅仅在多铎向扬州进军的路上，就有大批的汉人军队前来投靠，降军总兵力接近十四万，若加上之前投靠多铎的汉人军队，这个数字则更惊人地接近了二十四万，远远超过了满人军队的数量总和。这其中，有些军队本应是响应史可法的招募而驻守在扬州前线的。 

……（《扬州十日记》的作者）杨秀楚一行人被押解到一处大宅的时候，他看到一名扬州女人衣着光鲜地在清军面前挑选被掳掠来的衣物，一副欣然自得的样子。每看到值钱的物品，她就向清军曲意逢迎，媚态乞取，毫无羞耻之色。杨秀楚听满州士兵后来曾对人说：“我们当年征服高丽的时候，曾掳掠高丽妇女数万人回满洲，其受尽屈辱而无一人投敌变节，何以堂堂中国，竟然无耻至此？”

#+HTML:<p align="right"> ——《扬州：选择与遗忘》  </p> 
#+END_QUOTE

投靠异族，屠杀同胞。那些在庙堂之上被激烈争吵的内容，比如”国家“、”民族“对于他们是否有真正的意义？

标准与现实的反差，让人想到了类似的场景：

一群想当和珅的儒生，却在言谈中把海瑞作为清官的标准。
）


-----------------------------------

而这些变态的要求，我没有在孟子的文章里见过，孔子的也没有。       

但有句话，我是见过的：

#+BEGIN_QUOTE
君之视臣如土芥，则臣视君如寇仇。
#+HTML:<p align="right"> ——《孟子•离娄篇下》  </p> 
#+END_QUOTE

韩圣人似乎没见过，哈哈。 
-----------------------------------

知道这些，也不能如何。充其量，看到孟老夫子尚且如此，当我们种下龙种，却收获跳蚤之时，不必太过愤恨罢了。（这里可以有双关） 
-----------------------------------

（上一篇儒家的故事是组建读书会的倡议日志第二部分，这一篇是儒家故事之二，全系列之四）

* 评论
#+BEGIN_EXAMPLE


崔迅铭2013-08-16 13:10
我觉得文章里所讲的问题不是由于后世儒家堕落才导致的，而是一开始就困扰着儒家道德体系的，忠是好的，可是不是应该为了忠而吃人，孝是好的，可是应不应该为了孝而埋儿，这些问题，本质上与饿死事小失节事大都是同构的。说白了，这些其实都是基于儒家伦理的基本原则（忠孝守节），对某一规范做出的强势肯定，跟孔子讲的杀身成仁，孟子讲的以身殉道，没有本质区别。我们现在觉得难以接受，更多的是因为现代人身处不同道德体系内部，处于统摄地位的伦理原则发生改变的缘故。

崔迅铭2013-08-16 13:13
其实孟子自己也面临过类似的问题，任人有问屋卢子的礼与食孰重，就具有类似的性质。

崔迅铭2013-08-16 13:24
我觉得文章里所讲的＂为忠吃人，为孝杀人＂的问题不是由于后世儒家堕落才导致的，而是一开始就存在于儒家道德体系中的，忠是好的，可是不是应该为了忠而吃人，孝是好的，可是应不应该为了孝而埋儿，这些问题，本质上与饿死事小失节事大都是同构的。说白了，这些其实都是基于儒家伦理的基本原则（忠孝守节），对某一规范做出的强势肯定，跟孔子讲的杀身成仁，孟子讲的以身殉道，没有本质区别。我们现在觉得难以接受，更多的是因为现代人身处不同道德体系内部，处于统摄地位的伦理原则发生改变的缘故。其实孟子自己也面临过类似的问题，任人有问屋卢子的礼与食孰重，就具有类似的性质。

赵骥2013-08-16 14:00
回复崔迅铭:先感谢崔会长这么认真的回复谄笑。首先我很同意＂为忠吃人，为孝杀人＂出现的可能性是一开始就存在于儒家道德体系中的。既然孔子讲杀身成仁，孟子讲以身殉道，他们应该也会说”为忠可不可以杀人，为孝可不可以杀人？“的问题时候，说”可以“。这个问题的理解，有些像劝齐伐燕一节，“沈同问‘燕可伐与’，吾应之曰：‘可’。彼然而伐之也。彼如曰：‘孰可以伐之？’则将应之曰：‘为天吏，则可以伐之。’”，为忠孝可以不可以死节，可以，但要问是什么样的忠和孝。对不爱臣民的天子的忠，值不值得这种代价。其实正如屋卢子一段中“不揣其本，而齐其末，方寸之木可使高于岑楼“的比喻，我不是说为忠绝对不可以死，为孝绝对不可以死，这个问题的本质，是后世对于忠与孝的权重太高了，而这种过度拔高，在“民为贵，社稷次之，君为轻”和“君子不以其所以养人者害人”的孟子那里，还不存在。 

崔迅铭2013-08-16 15:07
回复赵骥: 这好不太一样，伐燕是一种行为，当这种行为符合道德原则时可取，违背道德原则时不可取。但忠孝节是伦理原则，很难做出像你所说的那种权衡和让步。在什么样的情况下应该忠，在什么样的情况下可以不忠，在什么样的情况下应该守节，在什么样的情况下可以不受节，这样的权衡与让步，会为不忠不孝不守节提供太多的借口，除非有明确的上位道德原则统摄，否则在一个道德体系内部容纳这样的权衡与让步是很难想像的。在儒家体系内问什么情况下可以不忠不孝，大概就相当于问一个现代人什么情况下可以罔顾人权，什么情况下可以侵害无辜者的生命，是很难获得在道德上没有争议的答案的。

赵骥2013-08-16 15:52
回复崔迅铭:其实孟子本人在道德体系里很是允许权衡变通的，同样有例子，比如“嫂溺援之以手”一节：淳于髡曰：“男女授受不亲，礼与？”孟子曰：“礼也。”
曰：“嫂溺，则援之以手乎？”曰：“嫂溺不援，是豺狼也。男女授受不亲，礼也；嫂溺，援 之以手者，权也。”曰：“今天下溺矣，夫子之不援，何也？” 曰：“天下溺，援之以道；嫂溺，援之以手——子欲手援天下乎？“
男女授受不亲同样是礼法要求，是儒家重要原则，原则之间矛盾，必然有权衡有例外。
诚如你所说，这样的道德体系会造成太大的自由度，但对“爱民”与“忠君”的矛盾，孟子已经用“民为贵，社稷次之，君为轻”给出了上位道德原则。所以，后世的行为，不是亚圣本意。
另外，孟子对于什么情况下不忠，还是说的了几个很清楚的情况的，君主不仁可以不忠“君之视臣如土芥，则臣视君如寇仇”，不食君之禄可以不忠”我无官守，我无言责也，则吾进退，岂不绰绰然有余裕哉“，这个话题，倒也不是全然的禁区。

牛学森Andrew2014-01-10 09:43
回复赵骥:就因为这些言论，孟子各种被阉割

赵骥2014-01-10 09:44
回复牛学森Andrew：比如说朱重八就看着这些巨不爽~那感觉应该就像老毛看鲁迅的文章一样~

牛学森Andrew2014-01-10 09:46
回复赵骥：应该是，孟子的言论算是比较激进了，其实我觉得孔子是恢复周礼，整个的世界观是向后的。孟子在这一点上恐怕有本质不同

赵骥2014-01-10 09:49
回复牛学森Andrew：可能是战国的氛围导致的吧，各家的演变都是走向偏激，你看庄子相对于老子也偏激尖刻得多~老子讲小国寡民，也是复古，庄子的目标就是打破某些东西了

牛学森Andrew2014-01-10 09:51
回复赵骥：有可能，战国后期太不和谐了，动不动就死个上万人。处在这个环境，改变世界的愿望是很强烈的。法家脱胎于道家，这本身就很奇葩啊

赵骥2014-01-10 13:02
回复牛学森Andrew:所以我觉得战国的书比春秋时写的书好看，情感充沛~法家这事儿吧，代表人物是荀子的弟子本身也很奇葩。道家留下可阐释的空间太大了，比如说把《老子》解释称大人之学，治国之术什么的，最奇葩的我记得有人说老子是兵书╮(╯_╰)╭。

牛学森Andrew2014-01-10 13:08
回复赵骥:比起说老子的阴阳是零和一，然后认为他开辟了现代计算机理论的人来说，已经是正常的了……

赵骥2014-01-10 19:32
回复牛学森Andrew:╮(╯_╰)╭，还有人说二进制创始人是伏羲，这话跟，宇宙创始人是思密达，听起来差不多… 

牛学森Andrew2014-01-10 19:37
回复赵骥：哈哈，是有一拼！

#+END_EXAMPLE
