#+TITLE: 写个佛家的故事
#+DATE: 2013-08-14 00:07 
#+TAGS: 人人网, 读书, 故事
#+CATEGORY: 
#+LINK: 
#+DESCRIPTION: 
#+LAYOUT : post


#+BEGIN_EXAMPLE
有人说：任何被大众长期传播、广泛接受的宗教，几乎只有一种样子。
#+END_EXAMPLE
#+HTML:<p align="right"> ——题记 </p>
据说（这次不是瞎说了，见《杂阿含经》）：
#+BEGIN_QUOTE
曾经有一面“阿能诃鼓”，音韵悠扬，声闻四十里。

累年敲打，鼓皮破败，鼓手用了一块新牛皮，修好了他。

经年累月，如是者数十次……每个部件都被换过一次的时候，

我们仍把这面鼓叫做阿能诃鼓，但，这还是当初的那面阿能诃鼓么？ 
#+END_QUOTE

这是个寓言，但在佛教史上有真实的对应（出于《付法藏因缘传》）：
#+BEGIN_QUOTE
佛陀最知名的几位弟子之一的阿难，在佛陀去世没多久之后便遇上这样一件事情： 

阿难走入一篇竹林，听到有比丘在念诵佛法偈语： 
#+BEGIN_VERSE
若人生百岁，不见水老鹤。 
不如生一日，而得睹见之。 
#+END_VERSE

阿难听过之后“惨然而叹”，连忙打断了那位比丘，对他说：你念错了，真正的佛谒是这样的： 

#+BEGIN_VERSE
若人生百岁，不解生灭法。 
不如生一日，而得解了之。 
#+END_VERSE

这位比丘听了阿难的佛偈，回去以后就说给自己的师父听。师父却说：“阿难老朽，脑子不灵光了，说话总是说错，不要信他的，以前我教你怎么念的你还接着怎么念去！” 

这位比丘听了老师的话，又继续念他的“不见水老鹤”去了。 
#+END_QUOTE
佛法难闻，不是么？

这是个很普遍的寓言，完全不限于佛教。就如我在组建读书会的倡议日志中引过的那样
#+BEGIN_QUOTE
那些所谓儒家思想、孔子真义，其实和孔子本人并没有太大关系…真正发生巨大影响的却是何休版孔子、杜预版孔子、郑玄版孔子、孔颖达版孔子、朱熹版孔子、王阳明版孔子… 
#+END_QUOTE

那么当我们谈儒家思想的时候，究竟是孔孟本意，还是经学衍变？

那些坚信是儒家是传统文化主体的重要来源之一，至今日仍影响中国人性格的人们，不会喜欢第一种定义。而后者，无论哪一种思想、文化、学说，在大一统的政治体制下面都会被阉割，然后变成相似的面貌，（这个结论，容后再讲个故事阐释）。如果这也可以叫儒家，那么，其实他也可以叫法家，叫阴阳家，叫社会活动家╮(╯_╰)╭。它可以是任何东西，所以它什么都不是。

由于这笔乱帐，我一直觉得那些动辄称儒家文化如何如何的人…很牛逼。

--------------------------------------------

那么，在中国的历史上，什么是佛教？

佛传佛法，传的是“了生死，出三界“看破之法，众人礼佛，求的是世间的荣华富贵；

佛传四法印，“诸行无常。诸法无我。涅槃寂静。有漏皆苦”。

众人九叩首，心心念念间有一恒常之我，斋戒敬奉，为“我”求个，现世富贵，来世荣华。

佛讲因果，是有果必有因，是客观规律

人讲因果，是行善得善报，是道德交易。

#+HTML: <br>

根本区别是，佛传的是智慧，人拜的是神通。

佛门是不支持造像的，"诸行无常，诸法无我"，你用泥塑木雕，留住表象声色，又算怎么个意思？

再讲个故事作例证吧，《景德传灯录》里就说：

#+BEGIN_QUOTE
达摩祖师传法东土，一苇渡江之前，在南京见梁武帝

梁武帝说：我广修佛寺，刻布经书，勤宣佛法，僧员日益，大师你看我有多大的功德？

达摩：没有功德。

梁武帝说:啥？

达摩：人天小果，有漏之因，如影随形，虽有非实。 

梁武帝再问："那真正的功德呢？" 

达摩回答说："净智妙圆，体自空寂，如是功德，不以世求。"

#+END_QUOTE

这段对话发生后，嗯，我猜达摩是被“南朝四百八十寺”气的去渡长江的…佛陀再一次地输给了人性。

#+HTML: <br>

相类似的，基督教的初期也是反对造像的，不仅反对，而且严禁。

后来？我们看到了大量的雕像绘画，不仅有耶稣的，还有圣母的，还有圣徒的。

我们只能表示哈哈。

#+HTML: <br>

人需要一个具体的形象，来寄托，来祈祷，来匍匐于它的脚下寻求安慰，人其实不太需要对现世的解脱智慧，但很需要高高在上的神灵。（三大宗教，貌似也就伊斯兰教目前还保持着对图像化穆罕默德的禁令，嗯，加油）

-------------------------------------      

 不幸的是，上面的恶意揣测在历史中一次又一次被证实，于是，我们似乎不得不悲哀地同意下面这两句话：

 #+BEGIN_QUOTE
 无论古今中外，任何在大众被广泛传播的思想，只要长时间地发展下去，最后的样子都会差不多——都会形成2点共性，一是神灵保佑，一是偶像崇拜。

 哪怕某种思想最初甚至是明确反对神灵保佑和偶像崇拜的，最后一样也会落到这个套路中去。 
 #+END_QUOTE

----------------------------------------

 结尾还是要有正能量的。当佛陀的思想都被流传异化如斯的时候，当你意识到也许理解的代价是被误解的时候

 没人读你的文章，听你说话，其实，也没那么惨。

 被有意或无意的错误解读，会更让人不愿接受。

 这种告诉你所有选择都不怎么样的思路，很佛家，不是么？

 有情皆苦，所以宽恕，嗯╮(╯_╰)╭

----------------------------------------

 看完本文，如对这个问题有兴致，推荐去读熊逸的《八戒说禅》，嫌长的话，可以改读《人间佛国》。

-----------------------------------
后记：

今天回顾了一下，上篇征婚的日志阅读量 =1560=

而上上篇日志《读书，自娱自乐的系列4》的阅读量—— =16=

我向你们保证，就算我把上图中的“我操操…”发成日志，阅读量也肯定是这个数的两倍…╮(╯_╰)╭

这些东西是没人看的，大家用脚投票表示，更喜欢看我吐槽、耍贱、四处黑。

于是，我决定今后一篇读书日志搭配着一篇传记发…算作捆绑销售。

讲个法家的故事是第一篇，组建读书会的倡议日志第二部分算是讲了一个儒家的故事，那么，这一篇是故事系列之三。

* 评论
#+BEGIN_EXAMPLE
李铮【怨念】2013-08-14 01:22
阅。

牛学森Andrew2013-08-14 11:44
特修斯之船无处不在，真理总有一定程度的普适性

赵骥2013-08-14 11:52
回复牛学森Andrew:还是牛局懂我~谄笑我一开始想找个本土化的故事来着，想了半天发现好像中国古人没谈过这个问题~

牛学森Andrew2013-08-14 13:50
回复赵骥:想了想，好像真的没人谈过。不过易经里持的观点就是事物不断变化。因此我觉得这说明我国古人是这么想的：船本来就需要换零件，这个事实本身就是“船”这个概念的一部分，船能开不就行了，不要自我蛋疼嘛

赵骥2013-08-14 14:11
回复牛学森Andrew:这也就是李泽厚总结中国人的特点“实用理性”~有道理赞，特修斯之船、阿能诃鼓，说的都是名词辨析，概念定义的问题。而最有可能提出来这个思想的是名家，但“坚白论“”白马非马“因为不实用，所以没有发展起来。

牛学森Andrew2013-08-14 14:13
回复赵骥：公孙龙有点生不逢时，兵荒马乱的春秋战国，他的理论市场不大。要搁在魏晋时代，估计有机会名垂青史

赵骥2013-08-14 14:18
回复牛学森Andrew：估计比王弼的名气大

牛学森Andrew2013-08-14 14:19
回复赵骥：王弼主要是解周易，公孙龙基本是自己原创，目测更胜一筹

赵骥2013-08-14 14:21删除 赞
回复牛学森Andrew：没准儿能发展出一套和西方逻辑学，印度因明学三足鼎立的名家学说谄笑可惜人们只有在吃饱了的时候才有空闲思考这些问题啊~

牛学森Andrew2013-08-14 14:23
回复赵骥：嗯，对的啊
#+END_EXAMPLE
