#+BEGIN_COMMENT
.. title: 仪式与教育
.. slug: yi-shi-yu-jiao-yu
.. date: 2013-10-31 11:29:25 UTC+08:00
.. tags: 人人网
.. category: 
.. link: 
.. description: 
.. type: text
#+END_COMMENT

#+OPTIONS: toc:nil

#+BEGIN_EXAMPLE
整理格式自己发一遍…原因是，分享下的评论都在关注称呼，没有人要关注下文章吗… 
#+END_EXAMPLE
又到一年129 ，又到一年合唱时。

不知道有没有人和我一样的好奇。拜年、扫墓、唱红歌，所有这些仪式其实都没有实质作用， 那人们为什么还需要仪式？

* 一

在高中，人们都渴望大学的自由。

在大学，每年的校内上都会有“原班人马回高三”的状态。

很多人在怀念：同学的深情，奋斗的激昂，单纯的心境。

------------------------------------------------

高三的天空，太狭小，人们飞翔的方向都如此的一致。

到了大学才发现，这世界太自由，自由到你往往找不到人跟你一起走。

是的，你知道我指的是什么，在现代社会带来的自由中，人们太容易孤独。

* 二

这个时候，人们会求助于仪式。

比如，在演唱会中，台下数万观众随着台上歌手同唱一首歌，听到自己的声音融进万人声浪中，会让他们感到归属。

再比如，中原大战后，张学良将军加入国民党阵营的表示，就是飞到南京，亲谒中山陵，以示继承总理遗教。

《礼记•曲礼》说“是故圣人作礼以教人，使人以有礼，知自别于禽兽。”而孟子说“人之所以异于禽兽者几希，庶民去之，君子存之。”做到礼，你就是君子，别人也会认为你是君子。而儒家的礼中，很大一部分就是仪式的规范，通过仪式，人完成了自我定位与群体认同。

--------------------------------------------------------------

这就是仪式最基础的作用，我们通过同样的行为，表达、确认和巩固一个群体的共有价值观和信仰，驱逐孤独，强化连接，建立归属感。

知乎上有个答案说的很好：人类如果没有共同的价值观念和信仰，就不会有仪式。而没有仪式，人类所建立起来的共有价值观念和信仰就无法集体性传承，结果必然是背离与异化，最终消亡。

* 三

讲完了仪式的意义，回到事件本身，在这个时代，我们能从 129 中继承怎样的价值呢？

--------------------------------------------------------------

这个时代，我们这些人，都有一种质疑一切的禀赋。

我们会听到什么：社会不安全，媒体不真实，信仰根植于谎言，历史依赖于权力。

你要敢于质疑，才能不被欺骗。这个真理，我们已经被教师、媒体和骗子教过很多次了。

--------------------------------------------------------------

但这个真理还有另一面:

在这个时代你要入戏，才会有进取的动力，你要坚信一些东西，才能推动一些东西。

在这个人人都变的精明的时代，缺少的精神，叫做痴…

痴人，不是傻，却也不精明的人，才会为了与自己无关的人，在江湖奔走呼吁，在庙堂据理力争。

* 四

但不精明的人，在这个社会生活是很难的，因为他们人数太少，距离太远，所以很容易空虚寂寞冷。他们需要归属感。

韩愈老夫子给这种归属感起了一个名字，叫做“道统”。自孔孟以来，千载读书人，信仰的共同体。

这种共同体，出现在我们今天的话题中：

对，在道统的角度看，“一二九”不仅仅是作为学生的个体与军警代表的政府的冲突，而且是一种“道统”与“法统”之间的对抗。

--------------------------------------------------------------

道统，不仅是一些记忆，而且是一种力量。一种强大到与世俗权力的“法统”相抗衡的力量。

这种力量，不来源于权力，来源于信仰，固执与不惜死。

它不仅出现在近代。

它出现在明代读书人不怕死的怪象中。

它出现在整个中国历史，君权与相权的斗争中，

--------------------------------------------------------------

想要改变这个社会，需要有一种在质疑中保持坚信的勇气，无理由，从一而终的坚信。当我们迟疑软弱的时候，需要有种仪式，把当年华北街头的英雄气与我们连接在一起。

意气不死，吾道不孤。

* 五

社会心理学中，有一个概念叫做社会性习得，指的是那些不需专门教导，只要生活在社会中就潜移默化习得知识的过程。比如，犯罪是错的。

无论自愿、被迫还是下意识，我们每个人都在这个社会已形成的种种仪式中，建立连接，定位自我，传承记忆。影响不可怕，可怕的是，你意识不到他们。

--------------------------------------------------------------


仪式，我们创立了它，用它来驱赶孤独，增强勇气。

正如我们用泥土塑成偶像，又用它来寄托宗教情感一样。

我们赋予它价值，又从它身上取得价值。

#+BEGIN_QUOTE
咸阳原上英雄骨，半向君家养马来。

——李商隐《浑河中》
#+END_QUOTE

* 评论
#+BEGIN_EXAMPLE
赵骥2013-10-31 11:36删除 赞
@王亦舒  我觉得这样把小段落分隔开可能行文会更清晰一点？

张祎嵩2013-10-31 11:40
帮骥兄顶一下~当年班主任大军说过一句话，叫先有形式，再有内容。虽然可能用在好事上，也可能用在坏事上，不过这道理想来是不错的

赵骥2013-10-31 11:42
回复张祎嵩:谢谢嵩哥~~：）

张君2013-10-31 12:03
写得很好！

郑翔宇Amadeus2013-10-31 14:06
作为一个无可救药的浪漫主义者，厌恶集体主义的同时却对于仪式感有某种病态的偏好╮(╯_╰)╭

赵骥2013-10-31 14:19
回复郑翔宇Amadeus:比如买书买一套之类的强迫症~

王亦舒2013-10-31 16:35
回复赵骥:我本来就是用手机看的，所以一直还算清楚~

赵骥2013-10-31 18:16
回复王亦舒: 我用空行把每章里分了下层次，总觉得之前分得不够细

佘睿2013-11-02 11:10
死德性不改。总是妄图通过简单的事情表达复杂的想法。

赵骥2013-11-02 11:11
回复佘睿: 这不是为了降低门槛么,结果我自己发的还是没什么人读

牛学森Andrew2013-11-02 11:17
看了状态，拐进来看日志。骥爷蛋定，无须挂怀

赵骥2013-11-02 11:19
回复牛学森Andrew: 哈哈，反倒帮我宣传了自己的日志啦。抛去文章中的软文成分，求牛哥斧正。

牛学森Andrew2013-11-02 12:09悄悄话
回复赵骥:写的很好啊，我感觉你是想的多而写的少，文章充满余音，有冰山一角的感觉。估计129是戳到喷子的G点了，129的确也只是个形式的空壳，全是缝的蛋免不了苍蝇啊。我暗自揣测，窃以为把129换成天安门看升旗，则好得多。比方说参差荇菜，这个拿来做起兴就比较人畜无害……如果一个少女是采摘转基因玉米，估计关雎会被怒喷……

赵骥2013-11-02 12:17悄悄话
回复牛学森Andrew: 这是命题作文…辅导员让洒家给他写写篇129宣传日志…所以说是软文么，好多破事，只能要隐着写

赵骥2013-11-02 12:29悄悄话
回复牛学森Andrew: 那个有歧义，辅导员指邰扬

牛学森Andrew2013-11-02 19:29
回复赵骥:壮哉我辅导员
#+END_EXAMPLE
