#+TITLE: 写个儒家的故事之三
#+DATE: 2013-08-16 20:39 
#+TAGS: 人人网, 读书, 故事
#+CATEGORY: 
#+LINK: 
#+DESCRIPTION: 
#+LAYOUT : post



#+BEGIN_EXAMPLE
如果你一觉醒来，发现自己被“与多名女性发生或保持不正当关系”，就"愉悦"的闭上嘴听故事吧。（此处有双关，听懂请微笑） 
#+END_EXAMPLE
#+HTML:<p align="right"> ——题记 </p>

当你好不容易想正经点儿的时候╮(╯ ╰)╭，不管你想说什么，都发现前人之述备矣，是件很蛋疼的事情。

所以，这篇和上篇写个儒家的故事之二一样，吐槽是最具创新性的部分。区别是，本文的论据大多不靠谱，上篇还是努力严谨了一下，这篇就更像抒情（直说这篇日志就是把好几段吐槽攒起来的多好╮(╯_╰)╭）。

---------------------------

上一篇结尾落在“ 君之视臣如土芥，则臣视君如寇仇”。孟老夫子这跃跃欲试的样子， 就差替梭罗写一篇《论公民的不服从》了。

这话听起来好听，不过真把这种光辉的思想落实到具体行动中，那就是一个字“反”。人多了就起义，一两个就投敌。都不是什么光辉词。

---------------------------

中国第一个大汉奸是谁？

根据定义的不同，广义的说，是伍子胥，狭义的说，是李陵。

---------------------------

伍子胥的故事，应该是最著名的复仇故事了。满门被斩，过昭关一夜白头，路遇老渔翁、浣纱女，吹箫吴市，乞食长街，得遇阖闾，而后鱼肠剑刺王僚，终于掘平王墓，鞭尸三百。ok，这些曲折的剧情都是戏曲演义。

但父兄受戮，投奔吴国，率吴攻楚，直破郢都，这些事情都于传有之。

在历史里，伍子胥的出现，抹上了与后世的愚忠完全不同的色彩。不品评人物，但至少这件事情向各个君王提了个醒：对臣子好点儿，不然是要付出代价的。

我一直以为，春秋战国时代，言论相对自由、君臣相等和气，是”弑君三十六 ,亡国五十二“这样辛勤劳作的结果。

看看，即便是爱国主义这种价值观，没有了制衡都是可怕的。╮(╯_╰)╭

---------------------------

伍子胥还是民族内部矛盾，到汉朝大一统，忠这个词，就更不讲理了。

于是我们看到了李陵。

我还是很喜欢这个人的，因为那篇《答苏武书》。

（我知道这篇很可能是伪作，伍子胥的故事用戏曲演义，李陵的故事用托名之笔，可见这文章很不严肃，借他人杯酒，浇胸中块垒罢了。）

一般的降军之将，台词就两句，”队长，别开枪，是我“，”我当年是立过功的，我现在要戴罪立功“。

《答苏武书》前半段也是这剧情，怀旧加表功。

但后半段，这文章给了自己一个成为千古名文的理由。

---------------------------

因为它给出了第三句台词，“陵虽孤恩，汉亦负德”。文风凌厉，千年之下，犹令凛然。

对啊，自汉立国以来，”萧、樊囚絷，韩、彭菹醢，晁错受戮，周魏见辜“，谈什么，“汉与忠臣不薄”呢？ 

即便不忠当死，汉以何杀我？

---------------------------
#+BEGIN_QUOTE
男儿生以不成名，死则葬蛮夷中，谁复能屈身稽颡，还向北阙，使刀笔之吏弄其文墨邪？愿足下勿复望陵。 
#+END_QUOTE

很容易就想到，飞将军的决命之语 ”广年六十余矣，终不能复对刀笔之吏！“

结局已经决定，对于那群在高高庙堂上的人，没谁想知道大漠狂沙中什么是事实。

对于败军之将，事实不重要，冤屈不重要。

所以，为了尊严，我拒绝接受审判。我可以自杀，我可以投降，魂归绝域也好，孤独凄惨也罢，我不会给你以审判我的快感。

---------------------------


这篇吐槽文章，更得不出什么正能量的结论，顶多：万一凡人有幸经历了题记那样的高大上待遇，就面带微笑静静听完这个部分熟悉却全然陌生的故事。既然剧本不在你手里，你总可以通过罢演，表达你的轻蔑。

--------------------------- 

后记：

“远托异国，昔人所悲，望风怀想，能不依依！” 我想决绝如李陵，也还是会想找两个人一吐胸中苦闷，不然又哪会有这篇《答苏武书》呢。

#+BEGIN_QUOTE
嗟乎，子卿！夫复何言？相去万里，人绝路殊，生为别世之人，死为异域之鬼，长与足下，生死辞矣。幸谢故人，勉事圣君。足下胤子无恙，勿以为念。努力自爱。时因北风，复惠德音。李陵顿首。
#+END_QUOTE

郁结满胸，勤道珍重，大见伤感。决绝之情，不舍之谊，反复萦绕。
