#+TITLE: 曾经，谈就业不可耻，做饭很可耻
#+DATE: 2014-11-15 14:37:39 
#+TAGS: 人人网, 抽风
#+CATEGORY: 抽风
#+LINK: 
#+DESCRIPTION: 
#+LAYOUT : post

#+OPTIONS: toc:nil

* 一、 
两千多年前——

孔老夫子问子路等人：你们将来想找什么工作呀？[1]

孟子跟齐宣王说：君子怎么能靠近厨房呢？多血腥，多残忍。[2]

--------------------------

两千多年后——

”看，爷刚做的新菜！“

“什么？！就业？功利，浅薄，低俗！”


* 二、

孔老夫子不仅关心弟子就业，讲学中还现身说法：“富而可求也；虽执鞭之士，吾亦为之。”[3]

顺便提醒一下各位，老夫子周游列国的目的，是求职。

-----------

这就是儒家的教育方式，还有什么能比一个人安身之本更反映一个人志向、喜好和境界？

这还是孟子直接教我们的：做箭的唯恐不能够伤害人，造销甲的人却唯恐箭伤害了人，选择谋生职业不可不谨慎啊。（“故术不可不慎也”[4]）

* 三、

所以当我听到把“就业”与“理想主义”相对立的言论时，我突然觉得这种思路很可怕…

“人生不止眼前的苟且，还有诗和远方”，所以你怎么能问我“下一步应该往哪里走”？！

我说了十楼的建法，你居然问建一楼怎么做？！？！

-----------

顺便说一句，科研型大学的教职就这么多，就业不加引导，极大多数人的科研生命也就五年（哦，倒霉些的八年），我实在想不出来，这样难道更对得起名校责任或是师长心血什么的么？


* 四、

为了区分理想与功利，割裂了目标与途径…这算不算是泼脏水把孩子泼出去了。

不过，可以理解。
正如“君子远庖厨”的人，应该也确实没为吃饭发过愁。
* 附录
为了严谨点，还是标一下出典

[1] 《论语·先进》“子路曾晳冉有公西华侍坐” 

     2014-11-16注：有人刚向我提了个疑问，本章中有“吾与点也”一句，似乎和孔夫子一贯鼓励入世有所不同？历代都很注意这句话，笔墨官司打了不知凡几：宋儒有解释这是因为曾皙有“尧舜气象”，杨慎对比提出“三大疑”，等等。其中曲折又够一篇长文章了。在这儿引一下钱穆《论语新解》，作为参考而非定论：
    #+BEGIN_QUOTE
     盖三人皆以仕进为心，而道消世乱，所志未必能遂。曾皙乃孔门之狂士，无意用世，
     孔子骤闻其言，有契于其平日饮水曲肱之乐，重有感于浮海居夷之思，故不觉慨然兴
     叹也。然孔子固抱行道救世之志者，岂以忘世自乐，真欲与许巢伍哉？然则孔子之叹，
     所感深矣，诚学者所当细玩。 
    #+END_QUOTE
     顺便说一句，这句话的理解，对我这篇文章其实是没有影响的。

[2] 《孟子·梁惠王上》“君子远庖厨” 
[3] 《论语·述而》“富而可求也；虽执鞭之士，吾亦为之。如不可求，从余所好。”
[4] 《孟子·公孙丑上》

