#+TITLE: 浮生所欠止一死，尘世无由识九还
#+DATE: 2013-11-12 00:19:00 
#+TAGS: 人人网, 故事 
#+CATEGORY: 
#+LINK: 
#+DESCRIPTION: 
#+LAYOUT : post

#+BEGIN_EXAMPLE
这是两天前的旧文小修改重发，出于好玩儿的心态想看看，如果一篇文章的核心意象被删掉的话，文意会有怎样的变化
#+END_EXAMPLE

老规矩，文章题目是用来限定读者数量的。

先讲三个故事：
* 一
鲁迅说“我先前以为人在地上虽没有任意生存的权利，却总有任意死掉的权利的。”我深为然。

不过我错了。因为我忘了，死的位置不合适，会挡别人的路的。你都死了，还不让其他人好好活着，这很不厚道。
------------------------------------ 
我们没有选择是否出生的权利，我们也没恣意死去的权利。

人生常常的遭际，或因天则，或以人伦，自由不曾降临。从生到死，人人如此。

世界就是如此的恶意。

意识到这一点，我今天把之前因为意气之争删了的好友，全加了回来。相比之下，她们可爱多了。

------------------------------------ 
几个月来偏激态度的消除，靠得不是爱，而是更大的恶意。

挺有意思哈？
* 二
第二个故事是前两天写了篇日志，第一篇五毛软文。（除了在开篇和结尾藏了些私货，哈哈）

我自己分享的时候就说，这种名字俗还把软文两个字贴在脸上的日志…我自己看见这类日志都不会点进去的。
------------------------------------ 
没想到，居然火了。虽然，很多反对的评论，证明他们果然没有点进去。

我还饶有兴致地看着自己又一次上了树洞。
------------------------------------ 

执不同意见的人中很有些×队友，强调自由意志与自主选择，却要扑灭一切异样的声音。

有点好玩啊？
* 三
第三个故事是再前两天，跟校队的同学告了个别。 

过程呢，大概可以简化为，此二人对输北大后校队一片升平，颇不认可，一言不合，转身就走。这个说法很无趣，我们换个表述。

郑翔宇和赵骥两名同志，在不了解任何作战细节的情况下，因为负于北大而迁怒于校队队员，这意味着他们已经走上了wbf一样自绝于人民的道路。这就叫老而不死是为贼。

------------------------------------ 

嗯，用毛主席的话说，郑翔宇走了，赵骥走了，这两件事情都是值得高兴的。

居然没有人高兴。这什么场景？老妈说随意去玩吧，儿子不愿意，怎么看也觉得真扭曲… 

看不太懂喂？ 
* 四

为什么这三个故事要放在一篇日志里？ 

（真：因为单独放三篇日志都太短。）

误：丢了的东西才会被重视，强调的东西也许已失去。嗯，所有的故事都想讲一个缺少与重要的一体两面关系。

------------------------------------ 
想要的东西特别多，荣誉信念存在感，可在更大的悲剧面前，你发现这一切都不重要，你真的是在乎这些吗？抑或是，你看，他有。

自由的重要性不曾动摇，如果会在看到一篇软文，会选择用树洞攻击来捍卫立场，是否是对信念本身不够自信的表现呢？

------------------------------------ 
所以应该想一想：

当你想要一件东西，是因为好，还是因为穷；

当你高喊一句口号，是说给别人听，还是说给自己听。

这样，才不会被匮乏绑架自由意志，不会被口号遮蔽自省审视。

------------------------------------ 
当然，正如上一篇文章的“道统”不是写给所有人看的，这篇的“自由”和“自省”都不是给所有人看的，“姜太公钓鱼，愿者上钩”。不过，按我一般日志的浏览量，那些喷子们是不会看的到这篇日志啦。
* 五

最后，你看我把第三部分一直留着，如有校队同学读到这里，不妨想想：

郑翔宇和赵骥的退群，意味着他们重视什么？是说给别人听还是说给自己听呢？

有些人希望他们回来，意味着这些人想要什么？是因为好，还是因为穷呢？
