#+TITLE: 甚矣吾衰矣！怅平生，交游零落
#+DATE: 2014-05-27 00:08:12 
#+TAGS: 人人网
#+CATEGORY: 
#+LINK: 
#+DESCRIPTION: 
#+LAYOUT : post

#+OPTIONS: toc:nil
* 一
这次题目恢复了正常的晦涩，进来应该是都是老朋友。
--------------------------------------
上来，先致歉：

昨天的日志，无论内容、还是文笔，都略失水准。

除了“情怀”以外，第一个点和第三个点纯粹是凑数用的。

所以我今天把它下架了，换点儿干货。
--------------------------------------

要不，对不住还能对我日志保持兴趣的各位。

* 二

其实昨天敢发上来，除了赶着清锋明辩决赛日以外。

还想拿半成品做个实验。

一个关于态度的实验。
--------------------------------------

* 三、

对本质的好奇，是种兴趣。

吵架的本质是什么？
--------------------------------------
李松蔚在知乎专栏里举了个好玩的例子，http://zhuanlan.zhihu.com/lswlsw/19757806 

政府官员“只有遇上党争，才会有暗流汹涌的讨论和碰撞，这种时候就更像辩论赛了。每个人发言说的都是大道理，好逻辑，可那些道理根本都不用听，某和某同气连枝，谁和谁针锋相对，这才是最根本的东西。”

然后他来了一个思维实验，用动作概括对话。例子很传神，我大部分引在这里

#+BEGIN_QUOTE
打个比方说，甲拥护韩寒，乙拥护方舟子，两个人吵起来了。这时候我只要把他们的动作提炼出来：「他们在吵架」

「哦，甲和乙还在吵架，围绕刚才的主题，两个人都很愤怒。」

「丙支持了甲的意见，反对了乙的意见。」

「丁想换一个话题。哦，丁还对甲和乙表达了不满。」

「甲不换话题，继续跟乙吵架。现在戊开始攻击甲了。戊在讨好丁。」

这样翻译了一阵，大家不乐意了。「我没有在吵架，」甲说，「我只是在讨论。」

乙也点了点头，难得地和甲站到了一边：「我们只是就事论事地说韩寒方舟子。」

「甲和乙拒绝我的解释。」我对老外说。老外点了点头，示意他看懂了。

「好啦，我们还是来聊聊罗永浩的事情吧。」丁不耐烦地打断我们。

「丁还是想换一个话题。」我继续翻译。


#+END_QUOTE

作者说“当我们仔细考虑这段对话——哪怕是虚构的对话——我们不难看出，人类的行为永远是那么意图明显，直截了当，有时候不得已，才借助话语的内容来遮掩缓冲。”

* 四

我原以为，争吵，是因为他们不同意我的论点。

现在我怀疑，有些人是先讨厌我的态度，然后再去寻找论点的错误。

其实，鲁迅早就说过，“是先因为被人认为『可恶』，这才终于犯了罪。”
--------------------------------------
于是，我做了个小小的实验。

昨天日志，起首我放了一张“螳臂挡车”。

半年前的日志，通篇谈的是“一二九”合唱。
--------------------------------------
一左一右，嘿嘿。
--------------------------------------
去看两篇日志的全站评论，对比着去看动作，会比内容有意思。

论点、论述、语言，扔掉后，会看到一些不一样的骨架。

* 五

一年零十四天前，我在日志里问从系队到校队的人，想不想继续去看看更大世界？

“当然每条道路，越走下去越艰难。”

“比如说，你会发现也许等待你去改变的世界，本就充满了愚昧、谎言与自以为是。”
--------------------------------------
一年后这个问题可以再往下走一步，假设技艺的精进，让你可以战胜愚昧与谎言。

从辩论到辩论外，准备没准备好更大挑战？

比如你发现，立论周严，逻辑精悍，语言出鞘有光、归鞘有血——这些突然都不重要的时候。

如果你在辩论场下，也遇到了预设立场的人的时候。

没有了计时，没有了评委，没有了观众，怎么办？
--------------------------------------
总之，地图还很大，要不要再走下去看看？

* 六

用纯疑问句结尾，会不会有骗访问的嫌疑？

在某方面具体实用的结论，也是有的。

比如我们可以秉承着类似《教育不了傻X，不如赚傻X些钱》中的态度，去学学《乌合之众》。

简化版，就像 *不会哄女生就造不了垃圾站* 那篇文章示范的那样

#+BEGIN_QUOTE
苟利国家生死以，岂因祸福避趋之。我来晚了。知我罪我，其惟春秋。人民万岁。亲爱的对不起我错了。下次再也不敢了。这些就是态度。先别急着讲道理，第一反应应该是先讲态度。
#+END_QUOTE

* 七

上篇日志的修改增补版还会上架的，不过，要等六四以后了。



* 评论
#+BEGIN_EXAMPLE
黄杰2014-05-27 00:12删除
。。。虽然一如既往的看不太懂。。。还是一如既往的点进来啦╮(╯▽╰)╭

赵骥2014-05-27 00:25
回复黄杰: 立场比内容重要，辩手要学会对此不莫名其妙~

赵骥2014-05-27 00:26
回复黄杰: 大概可以这么理解
#+END_EXAMPLE
