#+TITLE: 风雨忆同舟——我的清锋明辩反思录（1）
#+DATE: 2010-01-27 02:32:18
#+TAGS: 人人网, 辩论
#+CATEGORY: 
#+LINK: 
#+DESCRIPTION: 
#+LAYOUT : post


#+TITLE:     风雨忆同舟——我的清锋明辩反思录（1）
#+AUTHOR:    赵骥
#+EMAIL:     zhaoji-001@163.com.cn
#+DATE:      2010-01-27 02:32:18
#+DESCRIPTION: 
#+KEYWORDS: 
#+LANGUAGE:  zh_CN
#+EXPORT_SELECT_TAGS: export
#+EXPORT_EXCLUDE_TAGS: noexport
#+LATEX_CLASS: ctexart
-----------------

第一章    缘起
 
-----------------
这是一个巨陈旧的话题，快一年了，九字班的清锋明辩都要开始打了，写这个东西，太炒冷饭了吧。

然而，我感觉这个东西还是有记录下来的必要。因为我一直相信：一支队伍的成长，或者一个事物的发展，从自发到自觉的转变，是它迅猛成熟的前提。我又开始卖弄晦涩名词了,这是个很大的毛病，但一时没有更好的词，只好写上再解释一下吧，班门弄斧喽。
 
-----------------
自鲁迅先生开始，中国学术界很多人认为，“曹丕的一个时代”即魏晋时代了，是“文学的自觉时代”，之前是文学的自发时代，合乐而歌，诗经啊什么的，我不认为我在文学创作，我不过是自己舒服就唱，采风的官吏是把这个当政绩考查，民意调查什么的，也不把它当文学。文学依附着一大堆东西，乐舞啊，史料啊，什么的，反正不知道自己是文学，可以独立门户。到了魏晋，文人开始自发意识，我这个是文学创作，以西方语言来说，所谓为艺术而艺术的文人诞生了。

而魏晋之后，隋朝来的快走的也快，很快的就是唐朝，唐诗宋词，还有我们后辈模仿不已的唐宋文章，全是在这个时候。

有人这么说魏晋时代：“一个事物的发展由自发到自觉，由模糊混沌、朦胧无知到认识自己、反省自己，是一个质的飞跃，在事物的发展过程中具有非凡意义。”

扯了半天，不光是两个名词，顺便吹一下现在写的这个东西有多重要，呵呵。其实呢，自发到自觉确实是一个很重要的事，但是这篇日志能不能做到这一点呢，就不好说了。
 
-----------------
做这个东西，主要是考虑了队伍和我个人的原因。

队伍，自发到自觉这个东西已经说了。另外，虽然全队每个人基本都写了总结日志，但是有很多的东西没有写出来，大家主要是凝聚太多感情了吧，技巧就靠后放了。现在也许有必要把这些东西总结总结，收个尾，也让后面知道一下，我们是怎么走过来的，少走些弯路。最重要，也是它最可能发挥作用的方式，是当个靶子，让九字班有个攻击的目标，革命的对象，从而提升自己的能力。

从我个人而言，首先是进了校队，被老大培训过后，又多打了两场比赛，再加上对几场关键比赛（尤其四分之一和决赛）的思考，对有些东西有了些想法，纪录一下，希望对八字班其他人和九字班有用。走出工物，走入校队，你才能意识到过去的队伍团队意识多么强，自己的队友的强大的执行力，典范的淑女气质和儒雅风格，也才能知道曾经引以为豪的比赛中有多少不足，有多少不利于发展的东西。

其次，焦队为锻炼我组织能力让我当总教练，被我拒绝了；后让我带攻防，我再次拒绝了，现在焦鹏飞同学已经在做赛制了，我总得为队里做点儿事，于是开始写这个东西。其实为什么拒绝，我的经验没有一条可以放心教给九字班的，把孩子带坏的可能性太高，齐白石“学我者生，似我者死”，我的有些东西可能是“学我者死”，都太不成熟，而且个人痕迹太重。所以我感觉我更适合一个靶子的角色。我是一个靶子与标杆，虽然不是一个灯塔，不能明确告诉大家怎么走，但我在系内作为一个老辩手，我是一个参照系，九字班灭我的过程中，会有能力的提升，而灭了我之后，他们会知道自己的能力在哪里，对自己有一个清醒的认识。

第三，我太清楚自已可能会走下坡路了。我在很多东西上，和我比较推崇的先秦学派一样，早熟而且早衰，如果我在八字班辩手里现在还算不错的话，可能后劲不足。所以，可能我现在不写出来，以后就写不出来了，呵呵。
 
-----------------
这是个什么东西呢？八字班队史，不算，太多的主观判断，而且不是官方主修，焦队钦点，只是我自己的判断；回忆录，又不只是给八字班看的；教材，更不是了，很多东西根本就是头脑一个闪念，谁知道对不对，怎么能算教材呢？

总之，就是一点纪录，一点反思，一点经验，一点希望，杂糅出来的东西.

况且，焦鹏飞说，他不想让九字班受太多条条框框的束缚，会把一个队伍的特点磨掉。这话也对，于是我决定把这个东西放到网上来，九字班想看可以看两眼，不要受这个里面的经验之类的束缚。现在放上来，也主要是考虑九字班一开学就要打比赛了，要抢在之前写完。人家组了队开始打比赛了，你在这儿八字班八字班的不停，总给人一种借古讽今的意味：“你们过去打的怎么样怎么样，是不是嫌我们打的不好？”^_^
 
-----------------
在这个系列里，我想写一下，在我的理解中，我们队伍的风格，“重纠缠，重控场”，与我们每次用六成以上的时间在讨论的立论思路的沿袭习惯“攻防为上，”与优劣，以及我对辩题分析的想法（第二章）；在队内我们在互相扶持同时是如何彼此塑造的，是工物辩论队形成了我们各自的风格，每个辩位的战术作用、每个辩手的个人风格，以及要传递下去的东西（第三章）；以及对全系列五场比赛的回顾与讨论（第四到七章）；然后，写一点儿像这篇一样扯淡的话

- 第二章   立论与辩风
- 第三章   辩位与辩手 
- 第四章   分场分析之对电机与软院
- 第五章   分场分析之对法学
- 第六章   分场分析之对医学院
- 第七章   分场分析之对人文
- 第八章   总结
 
-----------------
虽然，这是一篇酝酿了很久的日志，思路有过很大的更改，很多想法都是推倒重来的，但是现在仍然只是一个草稿，我承认并且相信，现在而且将来一定会有人提出很多批评与改进。比如我希望队伍后面能够把更多的精力放在才气上，放在聪明上，不要过分强调杀伤力那些东西，也许九字班的人到我这个时候就会写“我被聪明误一生”，要走另外一条路。这其实是我的愿望，有比照有路标，人们才会知道自己正在走的是什么样的路。而这篇日志，而且我希望，最后有人能把这个东西完全推倒，重新立起一个更完整的体系来。那才是真正的自觉的过程。
