* 钱钟书
** 《槐聚诗存》
** 《谈艺录》
*** 序


 《谈艺录》一卷，虽赏析之作，而实忧患之书也。始属稿湘西，甫就其半。养疴返沪，行箧以随。人事丛脞，未遑附益。既而海水羣飞，淞滨鱼烂。予侍亲率眷，兵罅偸生。如危幕之燕巢，同枯槐之蚁聚。忧天将压，避地无之，虽欲出门西向笑而不敢也。销愁舒愤，述往思来。托无能之词，遣有涯之日。以匡鼎之説诗解颐，为赵岐之乱思系志。掎摭利病，积累遂多。濡墨已乾，杀青尟计。苟六义之未亡，或六丁所勿取；麓藏阁置，以待贞元。时日曷丧，清河可俟。古人固传心不死，老我而扪舌犹存。方将继是，复有谈焉。凡所考论，颇采“二西”之书，“二西”名本《昭代丛书》甲集《西方要纪?小引》、《鲒埼亭诗集》卷八《二西诗》。以供三隅之反。盖取资异国，岂徒色乐器用 ；流布四方，可徵气泽芳臭。故李斯上书，有逐客之谏；郑君序谱，曰“旁行以观”。东海西海，心理攸同；南学北学，道术未裂。虽宣尼书不过拔提河，每同《七音略序》所慨；而西来意即名“东土法”，堪譬《借根方説》之言。非作调人，稍通骑驿。附説若干事，则《史通?补注》篇固云：“除烦则意有所恡，毕载则言有所妨；遂乃定彼榛楛，列为子注。”萧志离乱，羊记伽篮，遗意足师，祖构有据。余既自叹颛愚，深惭家学，重之丧乱，图籍无存。未耄善忘，不醉多谬；蓄疑莫解，考异罕由。乃得李丈拔可、徐丈森玉、李先生玄伯、徐君调孚、陈君麟瑞、李君健吾、徐君承谟、顾君起潜、郑君朝宗、周君节之，或录文相邮，或发箧而授。皆指馈贫之囷，不索借书之瓻。并书以志仁人嘉惠云尔。壬午中元日锺书自记。

 右序之作，去今六载，不复追改，以志一时世事身事耳。初稿既就 ，余时时笔削之 。友好知闻 ，颇多借閲 ，且怂恿问世 。今承王伯祥 、叶圣陶两先生索付开明书店出版 ，稿只暂定 ，见多未熟 。周振甫、华元龙二君於失字破体，悉心雠正；周君并为标立目次，以便翻检 ，底下短书 ，重劳心力 ，尤所感愧 。余校閲时 ，见援据未备者数处。而排字已就，未宜逐处补阙。因附益於卷尾。民国三十七年四月十五日又记。
*** 小序

 余雅喜谈艺，与并世才彦之有同好者，稍得上下其议论。二十八年夏，自滇归沪渎小住。
 友人冒景璠，吾党言诗有癖者也，督余撰诗话。曰：“咳唾随风抛掷可惜也。”余颇技痒。
 因思年来论诗文专篇，既多刊布，将汇成一集。即以诗话为外篇，与之表裹经纬也可。比
 来湘西穷山中，悄焉寡侣，殊多暇日。兴会之来，辄写数则自遣，不复诠次。昔人论文説
 诗之作，多冠以斋室之美名，以志撰述之得地。赏奇乐志，两美能并。余身丁劫乱，赋命
 不辰。国破堪依，家亡靡托。迷方着处，赁屋以居。先人敝庐，故家乔木，皆如意园神楼，
 望而莫接。少陵所谓：“我生无根蒂，配尔亦茫茫”，每为感怆。因迳攘徐祯卿书名，不
 加标别。非不加也，无可加者。亦以见化鹤空归，瞻乌爰止，兰真无土，桂不留人。
 *立锥之地，盖头之茅，皆非吾有。知者识言外有哀江南在* ，而非自比“昭代婵娟子”也。
* 笔名
▪ 阿英 (原名:钱杏村)

▪ 艾芜 (原名:汤道耕)

▪ 艾青 (原名:蒋海澄)

▪ 巴人 (原名:王任叔)

▪ 巴金 (原名:李尧棠)

▪ 白桦 (原名:陈佑华)

▪ 冰心 (原名:谢婉莹)

▪ 丁玲 (原名:蒋冰之)

▪ 郭沫若 (原名:郭开贞)

▪ 胡适 (原名:胡嗣糜)

▪ 柳青 (原名:刘蕴华)

▪ 鲁迅 (原名:周树人)

▪ 老舍 (原名:舒庆春)

▪ 落花生 (原名:许地山)

▪ 鲁彦 (原名:王燮臣)

▪ 茅盾 (原名:沈雁冰)

▪ 秦牧 (原名:林觉夫)

▪ 柔石 (原名:赵平复)

▪ 绿漪 (原名:苏雪林)

▪ 田汉 (原名:田寿昌)

▪ 田间 (原名:童天鉴)

▪ 唐弢 (原名:唐瑞毅)

▪ 魏巍 (原名:鸿杰)

▪ 闻捷 (原名:赵文节)

▪ 萧军 (原名:刘鸿霖)

▪ 萧红 (原名:张乃莹)

▪ 西谛 (原名:郑振铎)

▪ 夏衍 (原名:沈端先)

▪ 殷夫 (原名:徐祖华)

▪ 叶圣陶 (原名:叶绍钧)

▪ 严文井 (原名:严文锦)

▪ 周扬 (原名:周起应)

▪ 邹韬奋 (原名:邹思润)
