#+BEGIN_COMMENT
.. title: 维基入口
.. slug: index
#+END_COMMENT
#+OPTION: toc:nil

『文件』绝对是很差很差的保存形式，无论是html，还是mht，还是屏幕截图。因为它们会让信息变得臃肿、难以一目了然，从而淹没信息的价值。我曾经保存过几百个mht网页，结果要找文章时非常痛苦，还不如重新上网搜关键词。

其次，『收藏』也是比较差的保存形式，无论是微信的文章收藏，还是知乎的收藏夹，都不推荐。尽管『收藏』功能非常方便，但你会发现那些东西你只是给它们做了个标签而已，它们还是原来的样子，还是别人的，并不是属于你的。随着你收藏的文章越来越多，『收藏』的价值也越来越低。

1) 喜欢的东西，复制到云笔记保存下来，掐头去尾，把花里胡哨的格式通通去掉，只留下最重要的信息本身。给文章起一个按自己方式理解的标题，如果有同类型文章也可以把关键段落凑在一起。
2) 隔一段时间就把那些看起来不再惊艳和佩服的文章删除掉，因为你的思想会进步，30岁回看20岁时呕心沥血的收藏会发现自己当年多么偏激和中二。评论性文章和鸡汤文尤其如此。
3) 不要舍不得删收藏。知识库臃肿对你一点好处也没有。
4) 不要收藏不明觉厉的文章，没法为己所用的知识再牛也没意义。
5) 你真的需要收藏的是那些你看懂了、觉得很有用、但一时没法消化完全的知识，或者信息量很大、以后可能还有些场合会需要引用到/拿来吹牛逼的知识，或者信息整理总结得特别好的文章，这些是最有价值的。等你完全理解和消化了文章的观点，变成自己的东西时，这篇文章留不留着反而不那么重要了，因为可能你自己都会写了。

* 计算机技术
- [[file:emacs.org][emacs]] 
- [[file:docker.org][Docker]]
- [[file:bibliography.org][bibliography 文献整理]]
- 
* 网络服务
- https://zoom.us/ 远程会议
* 软件

- VSO Downloader
  - 能够截取网页播放视频的流量，然后转换为视频，完全免费，没有广告
* 手机
 - 阅读 多看
 - 

* 系统
** windows 快捷键
 - Ctrl+L定位到地址栏并选中其中的文本，有个替代按键是Alt+D
 - CTRL+ESC：打开"开始"菜单
 - F3：查找所有文件
 - F4：选择"转到不同的文件夹"框并沿框中的项向下移动（如果工具栏在 Windows 资源管理器中是活动的）
 - F6：在 Windows 资源管理器中的窗格之间移动 CTRL+G：打开"转到文件夹"工具（仅限于 Windows 95 中的 Windows 资源管理器）
 - F10：激活菜单栏选项
 - CTRL+TAB/CTRL+SHIFT+TAB：在属性选项卡中移动
 - Win + C：打开控制面板
 - Win + K：打开"键盘属性"对话框
 - Win + I：打开"鼠标属性"对话框
 - SHIFT+右键单击：显示包含可选命令的快捷菜单
 - SHIFT+双击：运行备用的默认命令（菜单上的第二个项目）
 - ALT+ENTER：打开选定对象的属性
 - Windows 徽标+M：全部最小化
 - SHIFT+Windows 徽标+M：撤消全部最小化
 - Windows 徽标+D：最小化所有打开的窗口并显示桌面 
 - SHIFT+F10 打开对应于选定项目的快捷菜单（这与右键单击对象等效）
 - ALT+-（ALT+短划线）：显示多文档界面 (MDI) 子窗口的系统菜单（从 MDI 子窗口的"系统"菜单中，您可以还原、移动、最大化、最小化或关闭子窗口）
 - CTRL+TAB：切换到多文档界面 (MDI) 程序的下一个子窗口
 - CTRL+F4：关闭当前多文档界面 (MDI) 窗口
 - ALT+F6：在同一程序的多个窗口之间切换（例如，当显示记事本的查找对话框时，按 ALT+F6 可在"查找"对话框和记事本主窗口之间切换）
** linux 发行版
*** arch linux
自用的话推荐manjaro，我个人推荐manjaro的bspwm和i3wm版本，i3和bspwm是轻量级并具有高度可定制性的窗口管理器，配合conky食用更佳。似乎bspwm和i3都只能工作在xerver上。

bspwm是manjaro社区的一个大神做的，这个版本的目标是极致的轻量化和高效的图形界面体验，这个版本似乎应该说是面向技术人员power user的，不过这位大神对bspwm做了很多魔改让他更易用。另外技术支持很给力，在论坛上发帖回得很快，而且解释很详细。另外，bspwm版本没有使用display manager，因此开机登录会有一种神奇的体验，这个好处是从initcpio和内核被载入内存之后，到显示登录窗口，这个过程可以在10秒以内完成，当然，这依赖于自己编译的内核和自己生成的initpio，嗯……实际上initcpio也可以不存在。

相比之下，i3wm版本使用了lightdm，一个图形化display manager。i3wm版本开箱即用的体验比bspwm版本更好，首先是因为i3本身比bspwm更健全，另外i3wm的默认安装带的软件更多。

作者：云天明
链接：https://www.zhihu.com/question/48954561/answer/113953764
来源：知乎
著作权归作者所有，转载请联系作者获得授权。
*** 脱离鼠标操作计算机

Chrome的话，也可以用chrome Vim插件

把系统换成了Arch Linux，为了节约资源，窗口管理器使用了i3，这下不仅运行速度快了，
还彻底摆脱了鼠标。

我还在Macbook上外接了一台显示器，一边用Gvim写代码，另一边用
Firefox直接预览，两边都不需要鼠标。而窗口和显示器相关的操作，也都使用i3的快捷键
完成。这样不仅是效率提高的问题，因为避免了使用鼠标，所以手臂疲劳的问题也解决了。

回国后发现了一个新的Linux发行版：Manjaro，而它居然有直接基于i3的社区发行版（Manjaro i3 16.10），所以我建议题主可以直接安装这个，连Arch Linux安装过程中的诸多手动配置过程都可以省略了。可谓省心省力。
**** i3wm 
=sudo apt install i3 feh network-manager- xfce4-panel=
#+BEGIN_EXAMPLE
# Startups 
exec --no-startup-id feh --bg-scale $HOME/git/oh-my-i3/wallpaper.jpg
exec --no-startup-id nm-applet
exec --no-startup-id compton -cGbf
# xfce 面
exec --no-startup-id xfce4-panel --disable-wm-check
# start dmenu (a program launcher)
bindsym $mod+d exec dmenu_run
#+END_EXAMPLE

~/.compton.conf
#+BEGIN_EXAMPLE
# Shadow
shadow = true;
no-dnd-shadow = true;
no-dock-shadow = true;
clear-shadow = true;
shadow-radius = 6;
shadow-offset-x = -9;
shadow-offset-y = -9;
shadow-opacity = 0.4;
# shadow-red = 0.0;
# shadow-green = 0.0;
# shadow-blue = 0.0;
shadow-exclude = [ "n:e:Notification" ];
# shadow-exclude = "n:e:Notification";
shadow-ignore-shaped = false;

# Opacity
menu-opacity = 0.9;
inactive-opacity = 0.8;
frame-opacity = 0.9;
inactive-opacity-override = false;
alpha-step = 0.06;

# Fading
fading = true;
# fade-delta = 30;
fade-in-step = 0.03;
fade-out-step = 0.03;
# no-fading-openclose = true;

# Other
mark-wmwin-focused = true;
mark-ovredir-focused = true;
use-ewmh-active-win = false;
detect-rounded-corners = true;
detect-client-opacity = true;
refresh-rate = 0;
vsync = "none";
dbe = false;
paint-on-overlay = false;
sw-opti = false;

# Window type settings
wintypes:
{
  tooltip = { fade = true; shadow = false; opacity = 0.75; };
};
#+END_EXAMPLE
**** awesome 
=sudo apt install awesome=
*** linux 下设置键位 setxkbmap
=setxkbmap -option caps:super= Caps Lock becomes an additional Super (aka Win key).
